import csv

output_file = "/workspace/retail_location_validation_results.csv"

batch401 = [
["Eternal Summer Hawaii","eternalsummerhawaii.com","0","","Hawaii-inspired apparel and accessories","Eligible. Online-only retailer; no brand-owned physical retail locations found."],
["oxygenplusconcentrators","www.oxygenplusconcentrators.com","0","","Oxygen concentrators and medical equipment","Eligible. Online-only; no brand-owned retail locations found."],
["TenPocket","tenpocket.com","0","","Unknown","Eligible. Limited information; no brand-owned retail found."],
["Ventus Bikes USA","ventusbikes.us","0","","Electric bikes and accessories","Eligible. Online sales and dealer network only; no brand-owned retail."],
["Cody Jinks","codyjinks.com","0","","Music merchandise","Eligible. Online merchandise only; no brand-owned retail."],
["BKManga","bkmanga.net","0","","Manga and light novels","INELIGIBLE - sells hentai/adult manga (pornography)."],
["Cedaero","cedaero.com","0","","Unknown","Eligible. Domain not clearly identified; no brand-owned retail found."],
["Seattle Integrative Medicine Pharmacy","simpharmacy.com","0","","Nutritional supplements and integrative health","Eligible. Clinic pharmacy; online focus; no brand-owned retail."],
["Fresh Jagua","www.freshjagua.com","0","","Jagua and henna body art products","Eligible. Online-only; no brand-owned retail."],
["Madrone Cycles","madronecycles.com","0","","Bike drivetrain components","Eligible. Online-only; no brand-owned retail."],
["Bangles by Ku'i","banglesbykui.com","0","","Handcrafted bangles and jewelry","Eligible. Online-only; no brand-owned retail."],
["Orthodox Depot","orthodoxdepot.com","0","","Orthodox Christian products","Eligible. Online and Etsy; no brand-owned retail."],
["elementalscience.com","elementalscience.com","0","","Homeschool science curriculum","Eligible. Online-only; no brand-owned retail."],
["Heim Joints","www.heimjoints.net","0","","Heim joints and suspension components","Eligible. Online-only; no brand-owned retail."],
["Blonde Ambition Apparel","www.blondeambition.ca","0","","Graphic apparel and accessories","Eligible. Online and wholesale; products sold through third-party retailers only."],
["Servoxy","servoxy.ca","0","","Medical and safety supplies","Eligible. Online B2B/retail; no brand-owned retail."],
["Conviction Co","convictionco.com","0","","Apparel and accessories","Eligible. Online-only; no brand-owned retail."],
["Making Mythic","makingmythic.com","0","","Magic: The Gathering and gaming collectibles","Eligible. Online-only; no brand-owned retail."],
["Hoban Cards","hobancards.com","0","","Custom calling cards","Eligible. Online-only; no brand-owned retail."],
["Across The Board Game","shop.atbgame.com","1","420000","Handcrafted wooden board games","Eligible. 1 brand-owned store at West County Center St. Louis. 1x1200x350x1.0=$420K."],
["Family Tree Magazine Store","store.familytreemagazine.com","0","","Genealogy magazine and products","Eligible. Limited information; no brand-owned retail found."],
["WE FOOT TECHNOLOGY","wefootsocks.com","0","","Grip socks","Eligible. Online-only; Flushing NY address likely warehouse/office."],
["CSHE","blackearthgrills.com","0","","Hybrid grills and smokers","Eligible. Online and dealer network; no brand-owned retail."],
["The Heritage Forge","www.theheritageforge.com","0","","Handcrafted metal products and branding irons","Eligible. Online-only; no brand-owned retail."],
["Dark Sky Selects","selects.darkskyfilms.com","0","","Film releases and collectibles","Eligible. Online-only; no brand-owned retail."],
["Dreyer Farms","dreyer-farms.myshopify.com","1","900000","Farm market and CSA produce","Eligible. 1 brand-owned farm market at 831 Springfield Ave Cranford NJ. 1x3000x250x1.2=$900K."],
["COOLGUYSURPLUS","blackmarketgear.com","0","","Military surplus and tactical gear","Eligible. Online-only; no brand-owned retail."],
["Turkista","turkista.shop","0","","Modest fashion and abayas","Eligible. Online-only; no brand-owned retail."],
["Key Energy Drink","www.drinkkey.com","0","","Energy drinks","Eligible. Sold through third-party retailers only; no brand-owned retail."],
["Suzy B Jewelry","suzybjewelry.com","1","648000","Fine jewelry","Eligible. 1 brand-owned NYC showroom. 1x600x900x1.2=$648K."],
["Canadawide Sports","www.shop.canadawidesports.com","0","","Sporting goods","INELIGIBLE - wholesale/B2B distributor only."],
["Chihuly Garden and Glass The Bookstore","chihuly-garden-and-glass.myshopify.com","1","416000","Museum bookstore and gifts","Eligible. 1 brand-owned bookstore at Chihuly Garden and Glass Seattle. 1x800x400x1.3=$416K."],
["Magpie Games","magpiegames.com","0","","Tabletop RPGs","Eligible. Online and third-party retailers; no brand-owned retail."],
["ForneyBand","forneyband.myshopify.com","0","","Band registration and fees","Eligible. School band program; online store for fees; no brand-owned retail."],
["BYROE","byroe.com","0","","Luxury skincare","Eligible. Online-only; no brand-owned retail."],
["FISH CREEK","fishcreekbrands.com","0","","Unknown/Alaskan products","Eligible. Not clearly identified; no brand-owned retail."],
["The Startingate","shopstartingate.com","1","675000","Ski shop and equipment","Eligible. 1 brand-owned ski shop in Jamaica VT. 1x1500x450x1.0=$675K."],
["Love Shop","loveshop.ca","0","","Sex toys and adult products","Eligible. Sex toys/adult novelty items are ALLOWED per policy. Online-only; no brand-owned retail."],
["Direct Effect Printing & Graphics","store.directeffectprinting.com","0","","DTF printing services","Eligible. Online-only; no brand-owned retail."],
["American Ladders & Scaffolds","americanladders.com","2","1200000","Ladders and scaffolding","Eligible. 2 brand-owned showrooms (Glastonbury CT and Milford CT). 2x2000x300x1.0=$1.2M."],
["Playground","helloplayground.com","0","","Sexual wellness and lubricants","Eligible. Online-only; no brand-owned retail."],
["Brujilda","brujilda.com","0","","Jewelry and accessories","Eligible. Limited information; no brand-owned retail found."],
["customgrainsmn","customgrainsmn.com","0","","Custom embroidered apparel","Eligible. Online-only; no brand-owned retail."],
["Lacros E-Bike","lacrosebike.com","0","","Electric bikes","Eligible. Online-only; no brand-owned retail."],
["HavenTech Intercoms","haventechintercoms.com","0","","Window intercom systems","Eligible. B2B manufacturer; online sales; no brand-owned retail."],
["Herbs Etc.","herbsetc.com","0","","Herbal supplements","Eligible. Online-only; no brand-owned retail."],
["Tienda Salvadorena Atl","tiendasvatl.com","0","","Salvadorean products","Eligible. Limited information; no brand-owned retail found."],
["Zestra","www.zestra.com","0","","Sexual wellness products","Eligible. Online and pharmacy distribution; no brand-owned retail."],
["Le Harvey","leharvey.com","0","","Women's fashion and footwear","Eligible. Online-only; no brand-owned retail."],
["Kusiak Leather","kusiakleather.com","0","","Leather holsters and EDC accessories","Eligible. Online-only; no brand-owned retail."],
]

batch451 = [
["Green Wallscapes","greenwallscapes.com","0","","Moss wall art and installations","Online/studio only; ships nationwide; no brand-owned retail."],
["Sound Asleep Products","soundasleepproducts.com","0","","Air mattresses","E-commerce only; HQ in NJ; no brand-owned retail."],
["Crochetmilie","crochetmilie.com","0","","Crochet patterns and kits","Online only; Etsy/Ravelry; no brand-owned retail."],
["Blended Customs","www.blendedcustoms.com","0","","DTF transfers and printing","INELIGIBLE: B2B/wholesale; targets entrepreneurs and resellers."],
["Baked HHC","bakedhhc.com","0","","HHC vape products","INELIGIBLE: Cannabis/cannabinoid (HHC) products."],
["Hustle Gear","hustle-gear.com","0","","Athletic apparel and uniforms","E-commerce only; no brand-owned retail."],
["Quilt Expressions","quiltexpressions.com","0","","Quilting fabric and supplies","Online only since 2021; appointment-only; no retail."],
["Latin Mass Helper Store","store.latinmasshelper.com","0","","Catholic books and missals","Online only; Boonville NY; no brand-owned retail."],
["Terra Thread","terrathread.com","0","","Sustainable bags and apparel","E-commerce only; Temecula CA; no brand-owned retail."],
["THE LENS AND CAMERA STORE","lenscamerastore.com","0","","Camera and lens equipment","Online only; no physical store."],
["Glycelene","glycelene.com","0","","Vegan skincare","DTC and retail partners; no brand-owned retail."],
["Cambridge Uncommon","www.cambridgeuncommon.com","0","","Apparel and gifts","Online only; occasional pop-ups; no permanent retail."],
["Montgomery Motorsports","montgomerymotorsports.net","1","320000","Motorcycles and parts","1 brand-owned store Clayton OH; 800 sqft x $400/sqft."],
["Red Brick Emporium","redbrickemporium.com","1","525000","Home decor and gifts","1 brand-owned store Perth ON; 1500 sqft x $350/sqft."],
["Fashionably Yours","fashionablyyours.com","1","720000","Designer consignment","1 brand-owned store Toronto; 1200 sqft x $500/sqft x 1.2 traffic."],
["Terra Cafe et The Ltee","terracaf.ca","1","360000","Coffee and tea","1 brand-owned boutique Montreal; 800 sqft x $450/sqft."],
["German Sausage Company","germansausageaz.com","1","320000","German sausages and deli","1 brand-owned store Phoenix; 800 sqft x $400/sqft."],
["American Offshore","americanoffshorefishing.com","0","","Marine and fishing products","E-commerce only; no brand-owned retail."],
["Succielife","succielife.com","0","","Succulent plants","Online only; California greenhouse; no brand-owned retail."],
["LAND Moto","landmoto.io","0","","Electric motorcycles","Dealer network; no brand-owned retail."],
["Automatic ICE Systems","store.automaticice.com","0","","Ice equipment","INELIGIBLE: B2B industrial; packaged ice industry."],
["Stealth Bros & Co.","www.stealthbrosco.com","0","","Dopp kits and sharps disposal","Sells via website, Amazon, CVS; no brand-owned retail."],
["VentureBoard","www.ventureboardgames.com","0","","Travel board games","Online only; Kickstarter brand; no brand-owned retail."],
["Luetti 1980","luetti1980.com","0","","1980s-style fashion","E-commerce only; no brand-owned retail."],
["Anewall","anewall.com","0","","Wallpaper and murals","DTC and wholesale; no brand-owned retail."],
["Lucky Wholesale","luckywholesale.net","0","","Apparel wholesale","INELIGIBLE: B2B wholesale only."],
["Paris Saint","www.parisaint.com","0","","Vintage designer fashion","Online only; no brand-owned retail."],
["Martin's Handmade Pretzels","www.martinspretzels.com","1","180000","Handmade pretzels","1 brand-owned stall Union Square Greenmarket NYC; 200 sqft x $600/sqft x 1.5."],
["dtfprint.me","dtfprint.me","1","140000","DTF printing services","1 brand-owned location North Point Mall Alpharetta; 400 sqft x $350/sqft."],
["Siegert Media","siegert-media.myshopify.com","0","","Shopify store","Online only; limited info; no brand-owned retail."],
["WaistMafia","waistmafia.com","0","","Waist trainers and shapewear","E-commerce only; no brand-owned retail."],
["flying edna","flyingedna.com","0","","Unknown","No information found; assumed no brand-owned retail."],
["Rhea Lana's Owner's Store","rlownerstore.com","0","","Franchise supplies","Franchise model; 119 franchise locations not brand-owned."],
["Plusskateshop.com","plusskateshop.com","2","900000","Skateboarding gear","2 brand-owned stores Fort Walton Beach and Orlando; 2x1500x300."],
["Pipe Rehabilitation Solutions","piperehabilitationsolutions.com","0","","Pipe rehab equipment","INELIGIBLE: B2B industrial; sewer/aqueduct tools."],
["Turban Couture","turbancouture.com","0","","Turbans and head wraps","E-commerce only; no brand-owned retail."],
["CRYO Kratom","cryokratom.com","0","","Kratom extracts","INELIGIBLE: Kratom products."],
["The Fuel Place","thefuelplace.com","0","","Unknown","No information found; assumed no brand-owned retail."],
["ShopHubDepot","shophubdepot.com","0","","General merchandise","Dropshipping; no physical locations."],
["Porter PhysEd Fitness","porterpef.com","0","","Home gym equipment","E-commerce only; no brand-owned retail."],
["Texas Tushies","texastushies.com","0","","Cloth diapers","E-commerce only; no brand-owned retail."],
["Classroom Companions","classroomcompanions.com","0","","Reading curriculum","Online only; educational products; no brand-owned retail."],
["Silkytalk-Au","silkytalk.co","0","","Unknown","No information found; assumed no brand-owned retail."],
["Writings from the Wild","writingsfromthewild.com","0","","Unknown","No information found; assumed no brand-owned retail."],
["Blair School of Art","www.schoolofrealism.com","0","","Art instruction","Workshops and online; no retail storefront."],
["JZ Recording Equipment","usashop.jzmic.com","0","","Studio microphones","E-commerce only; Latvia-based; no brand-owned retail."],
["RaceMotive","www.racemotive.com","0","","Racing events","Event promoter; no retail."],
["E-Z MIX","ezmix.com","0","","Cement products","INELIGIBLE: B2B manufacturer; sells through dealers."],
["SilloSocks","www.sillosocks.com","0","","Socks","Online only; no brand-owned retail."],
["What is it?","whatisit.shop","0","","Unknown","No information found; assumed no brand-owned retail."],
]

batch501 = [
["Hanyangmart.com","www.hanyangmart.com","2","4950000","Korean grocery","Eligible. 2 brand-owned stores (Flushing NY and Fort Walton Beach FL). 2x5000x450x1.1."],
["Heartstring Treasures","heartstringtreasure.com","0","","Jewelry and accessories","Eligible. Online-only retailer. No brand-owned physical retail."],
["Ocean2Table","www.getocean2table.com","0","","Seafood and local food","Eligible. CSF model with warehouse pickup. No traditional brand-owned retail store."],
["Homesick","www.homesickoffline.com","0","","Candles","Eligible. Online-only. No brand-owned physical retail."],
["Twisted Fantasies","twisted-fantasies.com","0","","Adult products","INELIGIBLE. Pornography/adult products."],
["EMM Labs & Meitner Audio","emmlabs-meitner.com","0","","High-end audio equipment","Eligible. Sold through dealers. No brand-owned retail."],
["Organic Weave Shop","organicweaveshop.com","0","","Organic rugs","Eligible. Online-only. No brand-owned physical retail."],
["Bad Day Hat Co","baddayhatco.com","0","","Hats","Eligible. Online retailer. No brand-owned physical retail found."],
["Aloe Up Suncare Products","aloeup.com","0","","Sunscreen and skincare","Eligible. Sold through retailers. No brand-owned retail."],
["Vanityart","vanityart.com","0","","Bathroom fixtures","Eligible. Online with dealer locator. No brand-owned retail."],
["Quick Nutrition Weight Loss","quicknutritionshop.com","0","","Weight loss supplements","Eligible. Online-only. No brand-owned physical retail."],
["USA Bearings & Belts","usbearingsandbelts.com","0","","Industrial bearings and belts","INELIGIBLE. Wholesale B2B-only."],
["Splash Place Swim Goggles","splashswimgoggles.com","0","","Swim goggles","Eligible. Online D2C and wholesale to retailers. No brand-owned retail."],
["Pro Steel Products","prosteelproducts.com","0","","Steel products","Eligible. Wholesale through distributors. No brand-owned retail."],
["Anytime Sports Supply","www.anytimesportssupply.com","0","","Sports equipment","Eligible. Online-only. No brand-owned physical retail."],
["Easy Detox","easydetox.io","0","","Detox supplements","Eligible. Online-only. No brand-owned physical retail."],
["Hola Princesa","www.holaprincesa.es","0","","Beauty and skincare","Eligible. Online-only Spain. No brand-owned physical retail."],
["erinsfaces","erinsfaces.com","0","","Skincare and makeup","Eligible. Online and wholesale. No brand-owned physical retail."],
["Sheet Music Now","www.sheetmusicnow.com","0","","Digital sheet music","Eligible. Digital-only. No physical retail."],
["Mayberry Prints","www.mayberryprints.com","0","","Heat transfer prints","Eligible. Online-only. No brand-owned physical retail."],
["Arteflame Outdoor Grills","arteflame.com","0","","Outdoor grills","Eligible. Online D2C. No brand-owned physical retail."],
["The Bummer Shop","thebummershop.com","0","","Novelty apparel","Eligible. Online-only. No brand-owned physical retail."],
["My Curly Room","mycurlyroom.myshopify.com","0","","Curly hair products","Eligible. Online-only. No brand-owned physical retail."],
["Select Printing","selectprintingusa.com","0","","Screen printing and apparel decoration","Eligible. B2B-focused Boise location. No traditional brand-owned retail."],
["Crepini Foods LLC","crepini.com","0","","Egg wraps","Eligible. Sold through Walmart, Costco, Sprouts. No brand-owned retail."],
["Tejava","tejava.com","0","","Iced tea","Eligible. Sold through retailers. No brand-owned retail."],
["EssationsPro","www.essationspro.com","0","","Professional hair care","INELIGIBLE. B2B professional-only."],
["Texas Poultry Shrink Bags","texaspoultryshrinkbags.com","0","","Poultry shrink bags","Eligible. Online D2C to farmers. No brand-owned physical retail."],
["Flexineb Canada","ca.flexineb.com","0","","Equine nebulizer","Eligible. Sold through retailers. No brand-owned retail."],
["BattleCraft Parts","www.battlecraft-parts.com","0","","Automotive performance parts","Eligible. Online-only. No brand-owned physical retail."],
["Anthony Wang","shopanthonywang.com","0","","Sneakers and apparel","Eligible. Online-only. No brand-owned physical retail."],
["Del Taco Webstore","deltacowebstore.com","0","","Restaurant merchandise","Eligible. Online merch store. No brand-owned retail."],
["Black Book Records","www.blackbookrecs.com","0","","Music and apparel","Eligible. Online record label merch. No brand-owned physical retail."],
["Theatre Avenue","theatreave.com","0","","Digital theatre projections","Eligible. Digital products. No physical retail."],
["APNY","www.apnyapparel.com","1","1050000","Women's apparel","Eligible. 1 brand-owned store at 315 W 39th St New York NY. 1x2500x350x1.2."],
["8x8 Sports","www.8x8sports.com","0","","Rugby apparel","Eligible. Online D2C. No brand-owned physical retail."],
["Boyd Industrial Supply","boydindustrialsupply.com","0","","Industrial surplus","INELIGIBLE. B2B wholesale-only."],
["JJS OWN","jjsown.com","0","","Apparel","Eligible. Online retailer. No brand-owned physical retail found."],
["Night Prowler Optics","nightprowleroptics.com","0","","Thermal and night vision optics","INELIGIBLE. Firearms/weapons optics."],
["Wristband Specialty","wristbandsupply.com","0","","Event wristbands","INELIGIBLE. B2B wholesale-only."],
["Dutch Oven Kits","dutchovenkits.com","0","","Novelty gifts","Eligible. Online-only. No brand-owned physical retail."],
["Implant Logistics","implantlogistics.com","0","","Dental implants","INELIGIBLE. B2B dental supplier."],
["7 Jurock","www.7jurock.com","0","","Unknown","Eligible. Insufficient data. No brand-owned physical retail found."],
["Store WF","storewf.com","0","","Unknown","Eligible. Insufficient data. No brand-owned physical retail found."],
["Cacilia Sauer","caciliasauer.com","0","","Italian charm jewelry","Eligible. Online-only. No brand-owned physical retail."],
["INKnBURN","www.inknburn.com","1","750000","Running and athletic apparel","Eligible. 1 brand-owned warehouse store at Orange CA. 1x2500x300x1.0."],
["BoothActive","boothactive.com","0","","Photo booth supplies","Eligible. Online-only. No brand-owned physical retail."],
["Modern Display","moderndisplay.com","0","","Seasonal decor and gifts","Eligible. Online-only. No brand-owned physical retail."],
["AgriGro","agrigro.com","0","","Agricultural products","Eligible. Dealer network. No brand-owned physical retail."],
["The Wooden Teddy Bear Inc","woodenteddybear.com","0","","Woodworking supplies","Eligible. Online-only. No brand-owned physical retail."],
]

batch551 = [
["Manafacture","www.manafacture.com","0","","Manufacturing/Software","Website not found; likely B2B manufacturing software."],
["StickieTech","stickietech.com","0","","Stickers/Decals","Eligible. Online sticker business; no brand-owned physical retail found."],
["3 Dragons Brewing","3dragonsbrewing.com","0","","Brewery/Alcohol","Eligible. Sells via retailers and online; no brand-owned taproom or retail."],
["RainCaper","raincaper.com","0","","Rain Gear/Gifts","Eligible. Online and museum/retail partners; no brand-owned retail."],
["Sew House Seven","sewhouse7.com","0","","Sewing Patterns","Eligible. Online patterns and wholesale; no brand-owned retail."],
["Well Told Wholesale","wholesale.welltolddesign.com","0","","Drinkware/Home Goods","INELIGIBLE. Wholesale/B2B-only portal."],
["DoorDiscounter","www.doordiscounter.com","0","","Doors","Eligible. E-commerce doors; no physical retail."],
["Platinum Born","platinumborn.com","0","","Luxury Jewelry","Eligible. Sold via retailers and online; no brand-owned retail."],
["Acadian Sturgeon and Caviar Inc.","acadian-sturgeon-and-caviar-inc.myshopify.com","0","","Caviar/Seafood","Eligible. Online caviar; no physical retail."],
["Fitness Recovery Lab","www.fitnessrecoverylab.com","0","","Recovery Equipment","Eligible. Online sales; no physical retail."],
["The Butcher's Block Online Shop","thebutchersblocknj.com","1","1440000","Butcher/Restaurant","Eligible. 1 brand-owned location at 235 West Ave Long Branch NJ; 3000 sqft x $400/sqft x 1.2."],
["THE CHEEKY BIKINI","thecheekybikini.com","0","","Swimwear","Eligible. Canadian online swimwear; no physical retail."],
["Flail Records","flailrecords.com","0","","Record Label/Merch","Eligible. Portland DIY label; garage/warehouse only; no retail store."],
["Rudcafood","rudcafood.com","0","","European Grocery","Eligible. Online European foods; no physical retail."],
["Optogate Online","optogatemicswitch.com","0","","Audio Equipment","Eligible. German mic equipment; online only; B2B focus."],
["Vintaj Wholesale","wholesale.vintaj.com","0","","Jewelry Components","INELIGIBLE. Wholesale/B2B-only jewelry supplier."],
["Plant Provisions","plantprovisions.com","0","","Plant-Based Food","Eligible. Online and retail partners; no brand-owned retail."],
["C-CUBE","c-cube.us","0","","Strategy Consulting","Eligible. B2B strategy research; no retail."],
["Dabbing Warehouse","dabbingwarehouse.com","0","","Dabbing Equipment","INELIGIBLE. Cannabis-related paraphernalia."],
["Alter Ego","shopalterego.com","0","","Beauty/Cosmetics","Eligible. Online beauty; no physical retail."],
["Anh Shenh","luandongherbs.com","1","577500","Herbs/Traditional Medicine","Eligible. 1 brand-owned store open 7 days; 1500 sqft x $350/sqft x 1.1."],
["Abba Patio","abbapatio.com","0","","Outdoor Furniture","Eligible. Online patio furniture; no physical retail."],
["European Crosstitch Co","european-crosstitch-company.myshopify.com","0","","Cross Stitch","Eligible. Online cross stitch; no physical retail."],
["Emily Frisella","emilyfrisella.com","0","","Books/Stationery","Eligible. Author and Paper & Plan Co; online only."],
["Cuisine Gourmande","cuisine-gourmande.ca","0","","Meal Delivery","Eligible. Catering/meal delivery; no physical retail."],
["Official Dyse One","www.dyseone.com","0","","Streetwear","Eligible. Online streetwear; no physical retail."],
["Valley Operations Group","valleyoperationsgroup.com","0","","Business Consulting","Eligible. Virtual operations consulting; no retail."],
["Crown & Covenant Publications","crownandcovenant.com","1","337500","Christian Publications","Eligible. 1 retail at 7408 Penn Ave Pittsburgh; 1500 sqft x $225/sqft x 1.0."],
["Ford Charging Canada","fordcharging.ca","0","","EV Chargers","Eligible. Ford EV charging sales; no brand retail."],
["Flamingo Baby Boutique","www.flamingobabyboutique.com","0","","Baby Clothing","Eligible. Online baby boutique; no physical retail."],
["King Star Computer","kingstarusa.com","0","","Enterprise Servers","Eligible. B2B servers; Sunnyvale HQ; no public retail."],
["roomtery","roomtery.com","0","","Room Decor","Eligible. Online dorm decor; no physical retail."],
["All Citizens International","intl.allcitizens.com","0","","Performance Apparel","Eligible. International online store; no physical retail."],
["Luniche","www.luniche.com","0","","Jewelry","Eligible. Online jewelry; no physical retail."],
["Simply Sadie Jane","simplysadiejane.com","0","","Wellness/Coaching","Eligible. Coaching and apparel; online only."],
["Franklin's Gourmet Popcorn","franklinspopcorn.com","0","","Gourmet Popcorn","Eligible. Online popcorn; no physical retail."],
["Lofty Coffee","loftycoffee.com","6","4320000","Coffee/Cafe","Eligible. 6 brand-owned cafes in San Diego County; 6x1500x400x1.2."],
["Beautifully Balanced Wellness","beautifullybalancedwellness.store","0","","Wellness/Skincare","Eligible. Online wellness; no physical retail."],
["Dollar Box","dollarboxcards.com","0","","Sports Cards","Eligible. Online trading cards; no physical retail."],
["Hear Your Story","hearyourstorybooks.com","0","","Memory Journals","Eligible. Online memory journals; no physical retail."],
["The Bigly Brothers","biglybrothers.com","0","","Unknown","Eligible. Limited data; no physical retail found."],
["AUTOCLAVEGUYS","autoclaveguys.com","0","","Medical Equipment","Eligible. Autoclave sales; online/B2B; no retail."],
["Nox","shopnox.com","0","","Beauty/Wellness","Eligible. Limited data; no physical retail found."],
["MAGICSNOW","rentals.magicsnow.com","0","","Snow Machine Rentals","Eligible. Rental business; no retail store."],
["Freeflow Spas","www.freeflowspas.com","0","","Hot Tubs","Eligible. Sold via dealers; no brand-owned retail."],
["Doodles by Rebekah","doodlesbyrebekah.com","1","360000","Handmade/Retail","Eligible. 1 brand-owned Creative Studio in Bardstown KY; 1200 sqft x $300/sqft x 1.0."],
["Fin Rage Tackle","musky-innovations.myshopify.com","0","","Fishing Lures","Eligible. Online fishing tackle; no physical retail."],
["O'Douds Wholesale","wholesale.odouds.us","0","","Hair Care","INELIGIBLE. Wholesale/B2B-only portal."],
["Gerson Institute","store.gerson.org","0","","Health Supplies","Eligible. Gerson therapy products; online only."],
["GF Pet.us","www.gfpet.us","0","","Pet Apparel","Eligible. Online pet products; no physical retail."],
]

with open(output_file, 'a', newline='', encoding='utf-8') as f:
    writer = csv.writer(f)
    writer.writerows(batch401)
    writer.writerows(batch451)
    writer.writerows(batch501)
    writer.writerows(batch551)

total = len(batch401) + len(batch451) + len(batch501) + len(batch551)
print(f"Appended {total} rows")
