import csv
output_file = "/workspace/retail_location_validation_results.csv"

batch601=[
["Free Mom Hugs","store.freemomhugs.org","0","","Nonprofit merchandise","Eligible. Online-only store selling branded apparel. No brand-owned physical retail."],
["AVH Extentions & Wigs","allvirginhair.com","2","1540000","Hair extensions and wigs","Eligible. 2 brand-owned retail in Atlanta GA (Cobb and Camp Creek). 2x2000x350x1.1."],
["My Big Adventure","mybigadventure.com.au","0","","Travel diaries and accessories","Eligible. Online-only Australian retailer. No physical retail."],
["Light Poles Plus","lightpolesplus.com","0","","Commercial lighting","Eligible. B2B-focused eCommerce. No brand-owned retail storefront."],
["Park Hopper Design","parkhopperdesign.com","0","","Theme park apparel","Eligible. Online-only limited-time shop. No physical retail."],
["DS Distribution Center","ds-distributioncenter.com","0","","Logistics/warehousing","INELIGIBLE: Wholesale/B2B-only. 3PL warehousing and fulfillment."],
["Shop CB Lifestyle","shopcblifestyle.com","0","","Tableware and entertaining","Eligible. Online-only curated tableware. No physical retail."],
["Lara Wholesale","buylara.com","0","","Wholesale dresses","INELIGIBLE: Wholesale/B2B-only. B2B portal for retail stores."],
["Raw & Rebellious","www.rawrebellious.com","0","","Apparel and accessories","Eligible. Online-only apparel brand. No brand-owned retail."],
["2 Gypsy Sisters Boutique","2-gypsy-sisters-boutique.myshopify.com","0","","Personalized apparel","Eligible. Online-only Shopify store. No physical retail."],
["Grass & Bone","www.grassandbone.com.au","0","","Premium meat","Eligible. Online butcher with Sydney delivery. No physical retail."],
["KROK","krokcraft.com","0","","Mortar and pestle sets","Eligible. Online-only Thai handcrafted kitchenware. No physical retail."],
["Culinary by Hobby Hill","hobbyhillfarm.com","1","300000","Culinary classes and specialty foods","Eligible. 1 brand-owned store in Powhatan VA. 1x1500x200x1.0."],
["Pigeon Mountain Trading Company","pigeonmountaintrading.com","1","500000","Beekeeping supplies","Eligible. 1 brand-owned store in LaFayette GA. 1x2000x250x1.0."],
["Allegory Handcrafted Goods","allegorygoods.com","0","","Leather and wood goods","Eligible. Online-only handmade goods. No physical retail."],
["Curst kosmetics","curstkosmetics.com","0","","Cosmetics","Eligible. Online store. No brand-owned retail."],
["McKinley Leather","mckinleyleather.com","0","","Leather products","Eligible. Online-only personalized leather. No retail storefront."],
["Feiya Cosmetics","feiyacosmetics.com","1","525000","Skin care and cosmetics","Eligible. 1 brand-owned store in San Jose CA. 1x1500x350x1.0."],
["FortKnight Optics","fortknightoptics.com","0","","Tactical shooting glasses","INELIGIBLE: Firearms/weapons-related tactical shooting glasses."],
["PS","www.paigespiranac.com","0","","Golf/celebrity merchandise","Eligible. Online-only Paige Spiranac merchandise. No physical retail."],
["Hustleandheart.shop","hustleandheart.shop","0","","Sublimated blankets","Eligible. Wholesale application site. No brand-owned retail."],
["ForaCare Canada","shop.foracarecanada.com","0","","Health monitoring devices","Eligible. Online-only glucose/ketone monitors. No physical retail."],
["Bella Sleep Company","bellasleepcompany.com","0","","Sleep products","Eligible. Online-only sleep masks and earbuds. No physical retail."],
["Blue Water Conservation District","bluewatercd.org","0","","Conservation merchandise","Eligible. Conservation district with Shopify store. No brand-owned retail."],
["ImLivinB","www.imlivinbshop.com","2","1155000","Apparel","Eligible. 2 brand-owned stores: Buffalo NY and Charlotte NC. 2x1500x350x1.1."],
["Sonoma County Meat Co.","sonomacountymeatco.com","1","1125000","Meat and butcher","Eligible. 1 brand-owned butcher shop in Santa Rosa CA. 1x2500x450x1.0."],
["ASTERIA","asteriamask.com","0","","LED skincare masks","Eligible. Online-only LED masks. No physical retail."],
["Air Plant City","www.airplantcity.com","0","","Air plants","Eligible. Online-only air plants. No physical retail."],
["Savoy Tea Co","savoy-tea-co.myshopify.com","3","1080000","Tea","Eligible. 3 brand-owned stores: Fayetteville AR, Kansas City MO, Lenexa KS. 3x1200x300x1.0."],
["KUB Baby","kubbaby.com","0","","Baby products","Eligible. Online-only. No retail storefront."],
["Setadel Studios","www.setadelstudios.com","0","","Jewelry/art","Eligible. Online/eBay presence; no physical retail found."],
["Roy Henry Vickers Gallery","royhenryvickers.com","1","900000","Art and prints","Eligible. 1 brand-owned gallery in Tofino BC. 1x2000x300x1.5."],
["Grit Coffee","gritcoffee.com","9","4950000","Coffee","Eligible. 9 brand-owned locations in Virginia. 9x1000x500x1.1."],
["by Humankind","byhumankind.com","0","","Personal care","Eligible. Online DTC plus stockists. No brand-owned retail."],
["Evolving Textures","evolvingtextures.com","0","","Natural hair care","Eligible. Online-only natural hair products. No physical retail."],
["LullaLeisure","lullaleisure.com","0","","Kids sleep products","Eligible. Online-only kids sleep headphones. No physical retail."],
["Chefmaster.com","chefmaster.com","0","","Baking supplies","Eligible. Online/wholesale food coloring and baking. No retail storefront."],
["Neurochrome","neurochrome.com","0","","Audio amplifier kits","Eligible. Online-only DIY audio kits. No physical retail."],
["mylittlesonshineco","mylittlesonshine.co","0","","Personalized baby apparel","Eligible. Online-only. No physical retail."],
["Urban Farmhouse","theufbrand.com","1","450000","Home goods and beauty","Eligible. 1 brand-owned store in Geneseo IL. 1x1500x300x1.0."],
["KNG Motorsports","kngaero.com","0","","Automotive aero parts","Eligible. Online-only. No retail storefront."],
["PennBilt","pennbilt.com","0","","Unknown","Eligible. Limited public info; no retail locations identified."],
["Wound Care Mattress","woundcaremattress.com","0","","Medical equipment","Eligible. Online DTC and B2B medical mattresses. No physical retail."],
["Californo","www.californo.co","0","","Pizza ovens","Eligible. Online manufacturer. No traditional retail."],
["Le Goute Natural Spice","legoutenaturalspice.com","0","","Caribbean spices","Eligible. Online-only. No physical retail."],
["Lisette L Montreal - Canada","lisettel.ca","0","","Women's apparel","Eligible. Online and wholesale; sold in 5000+ stores. No brand-owned retail."],
["Redwood Cloth Company","redwoodclothco.com","0","","Cloth diapers","Eligible. Online-only. No physical retail."],
["Wildwood Grilling Outlet","wildwoodgrillingoutlet.com","0","","Grilling planks","Eligible. Online-only grilling products. No physical retail."],
["Orlando Informer Merchandise","merch.orlandoinformer.com","0","","Theme park merchandise","Eligible. Online-only merch. No physical retail."],
["OffCourt","offcourt.com","0","","Personal care for athletes","Eligible. Online-only DTC body care. No physical retail."],
]

batch651=[
["Russell Brothers Farm","russellbrothersfarms.com","2","432000","Grass-fed meats and farm products","Eligible. Brand-owned farm stands in Morganza MD and Clements MD. 2x1200x180x1.0."],
["ordinaryselenophile","www.ordinaryselenophile.com","0","","Unknown","Eligible. Could not verify business; no brand-owned retail found."],
["General Jackson's","genjax.com","0","","River cruise and dining","Eligible. Showboat/dining venue. Not retail; no product retail locations."],
["The Branded Vaquero","thebrandedvaquero.com","1","360000","Western apparel and accessories","Eligible. 1 brand-owned store at The Emporium Castle Rock CO. 1x1200x300x1.0."],
["Firebird Stamps LLC","firebirdstamps.com","0","","Metal stamping tools and supplies","Eligible. Online-only stamping supplies. No brand-owned retail."],
["Ski Lift Designs","skiliftdesigns.com","0","","Refurbished chairlift furniture","Eligible. Online-only. No brand-owned retail."],
["MELAS CLOTHING CO.","melasclothingco.com","1","280000","Women's apparel and swimwear","Eligible. 1 brand-owned boutique in Longview TX. 1x1000x280x1.0."],
["Majorwavezlab","majorwavezlab.com","0","","Unknown","Eligible. Launching Las Vegas; no open retail yet."],
["Bezier Games","beziergames.com","0","","Board games","Eligible. Online-only board game publisher. No brand-owned retail."],
["Pixel Surplus","pixelsurplus.com","0","","Design assets and digital products","Eligible. Online-only design resources. No brand-owned retail."],
["Wristbands Online","www.wristbandsonline.com","0","","Event wristbands","Eligible. Online; manufacturing facility. No brand-owned retail storefront."],
["prive products pro","priveproductspro.com","0","","Professional hair care","Eligible. Online-only salon-quality hair products. No brand-owned retail."],
["Brockton Gems","brocktongems.com","0","","Fine jewelry and gemstones","Eligible. Online-only jewelry. No brand-owned retail."],
["Sissy's Shop AL","sissysshopal.com","0","","Women's apparel and accessories","Eligible. Online-only boutique. No brand-owned retail."],
["Powercall Sirens LLC","powercallsirens.com","0","","Emergency sirens and firefighter gear","Eligible. Online-only. No brand-owned retail."],
["Jesse Brown's Outdoors","shop.jessebrowns.com","1","875000","Outdoor gear and fly fishing","Eligible. 1 brand-owned store at 4732 Sharon Rd Charlotte NC. 1x2500x350x1.0."],
["Lacy Boots","www.lacyboots.com","0","","Western riding boots","Eligible. Online-only; uses dealers. No brand-owned retail."],
["Vieler International LP","vieler.store","0","","Unknown","Eligible. Could not verify; no brand-owned retail found."],
["Bachelorette.com","bachelorette.com","0","","Bachelorette party supplies","Eligible. Online-only novelty party supplies. No brand-owned retail."],
["The Original Poop Bags","poopbags.com","0","","Eco-friendly pet waste bags","Eligible. Online-only pet products. No brand-owned retail."],
["Doatnut","doatnut.myshopify.com","1","360000","Gluten-free oat donuts","Eligible. 1 brand-owned bakery at 2530 Vista Way Oceanside CA. 1x800x450x1.0."],
["TAP & DYE","www.tapanddye.com","0","","Unknown","Eligible. Could not verify; no brand-owned retail found."],
["Holiday Warehouse","holidaywarehouse.com","0","","Holiday and event decorations","Eligible. Online-only seasonal decor. No brand-owned retail."],
["thestrongneck","thestrongneck.com","0","","Neck strengthening fitness device","Eligible. Online-only fitness product. No brand-owned retail."],
["Sweet Rollz Golf","sweetrollzgolf.com","0","","Golf putter grips and accessories","Eligible. Online and via pro-shop stockists. No brand-owned retail."],
["Onpharma Company","www.onpharma.com","0","","Dental buffering products","INELIGIBLE. B2B/wholesale dental supplier."],
["Sonrei","www.sonreiskin.com","0","","Suncare and sunscreen","Eligible. Online-only skincare. No brand-owned retail."],
["Exoticblinksaz","exoticblinksaz.com","0","","Eyelash products and lash supplies","Eligible. Online-only lash products. No brand-owned retail."],
["KoolR","www.koolr.com","0","","Wine cooling systems","Eligible. Online-only. No brand-owned retail."],
["DONNEE PAR DIEU","www.donneepardieu.com","0","","Unknown","Eligible. Could not verify; no brand-owned retail found."],
["Patriot Foods Inc.","patriotfoods.com","0","","US-grown farm foods","Eligible. Online-only farm market. No brand-owned retail."],
["Piper & Perro","piperandperro.com","0","","Unknown","Eligible. Could not verify; no brand-owned retail found."],
["SLIK Tripods","slikusa.com","0","","Photography tripods and equipment","Eligible. Online-only photo equipment. No brand-owned retail."],
["The Boob Tape","www.theboobtape.com","0","","Breast lift tape","Eligible. Online-only. No brand-owned retail."],
["Flower Days Florists","www.flowerdaysflorists.co.uk","0","","Florist arrangements","Eligible. Home-based studio; delivery/collection only. No walk-in retail."],
["Luxe Gemmes","www.luxegemmes.com","0","","Fine jewelry","Eligible. Online-only jewelry. No brand-owned retail."],
["Coast Roast Organic Coffee","coastroast.com","0","","Organic coffee","Eligible. Online-only coffee. No brand-owned retail."],
["Tatiana Irizar","tatianairizar.com","0","","Jewelry and hair care","Eligible. Online-only. No brand-owned retail."],
["PROTECTCOVERS","protectcovers.com","0","","Device and keyboard covers","Eligible. Online-only protective covers. No brand-owned retail."],
["house-plant-west","houseplantwest.com","0","","Houseplants","INELIGIBLE. Wholesale/B2B-only; serves plant stores and garden centers."],
["ETMall.TV","etmall.tv","0","","Unknown","Eligible. Could not verify; no brand-owned retail found."],
["SoundproofStore","soundproofstore.com","0","","Soundproofing and acoustic products","Eligible. Online-only acoustic products. No brand-owned retail."],
["Kalon Essential","www.kalonessential.com","0","","Hair and body care","Eligible. Online-only hair care. No brand-owned retail."],
["TrendyWristbands","www.trendywristbands.com","0","","Event wristbands","Eligible. Online-only. No brand-owned retail."],
["woodybeingllc","www.woodybeing.com","0","","Hand-carved wooden home decor","Eligible. Online-only artisan goods. No brand-owned retail."],
["Voll-Oko","voll-oeko.de","0","","Unknown","Eligible. Could not verify; no brand-owned retail found."],
["All Marble Tiles","allmarbletiles.com","1","500000","Marble and tile","Eligible. 1 brand-owned showroom at 175 Moonachie Rd Moonachie NJ. 1x2500x200x1.0."],
["Ovipost","www.ovipost.com","0","","Insect farming and protein","INELIGIBLE. B2B/wholesale; agriculture and animal feed."],
["Preserve","www.preserve.eco","0","","Sustainable household products","Eligible. Online-only. No brand-owned retail."],
["Black Knight","playbk.com","0","","Unknown","Eligible. Could not verify; no brand-owned retail found."],
]

batch701=[
["Serucell","serucell.com","0","","Skincare/cosmeceuticals","Eligible. Online D2C. No brand-owned retail."],
["cielos.la","cieloslosangeles.com","0","","Apparel/lifestyle","Eligible. Online-only clothing store. No physical retail."],
["CK Fight Life","www.ckfightlife.com","0","","Jiu jitsu/paintball gear","Eligible. Online-only. No brand-owned retail."],
["NC Paints","ncpaints.com","1","1050000","Paint/decorating","Eligible. 1 brand-owned Benjamin Moore store at 3808 Guess Road Durham NC. 3000 sqft x $350/sqft."],
["Blackballed Golf","blackballedgolf.com","0","","Golf apparel","Eligible. Online-only. No brand-owned retail."],
["The RAF Outfitter","outfitter.theraf.org","0","","NGO merchandise","Eligible. Online-only RAF merchandise. No physical retail."],
["Prime Kitchen and Nutrition","primemealprep.com","0","","Meal prep delivery","Eligible. Online meal prep with local pickup. No retail store."],
["Chesapeake Billiards","www.baltimorebilliards.com","1","700000","Billiards/game room","Eligible. 1 brand-owned showroom at 8906 Waltham Woods Rd Parkville MD. 2500 sqft x $280/sqft."],
["The Happy Place Shop","shophappyplace.myshopify.com","1","600000","Gift boutique","Eligible. 1 brand-owned store at 105-107 S. Union St Old Town Alexandria VA. 2000 sqft x $300/sqft."],
["Gauge-Life","gaugelife.com","0","","Unknown","Eligible. Limited web presence. Assumed online-only."],
["Kishkesh","www.kishkesh.com","0","","Baby apparel","Eligible. Online-only baby products. No physical retail."],
["Kori Krill Oil","shop.korikrilloil.com","0","","Supplements","Eligible. Sold via Walmart/Target/CVS. No brand-owned retail."],
["BarkerandBrowns","barkerandbrowns.com","0","","Unknown","Eligible. Domain not found. Assumed 0 retail."],
["OBTAIND","obtaind.com","0","","Unknown","Eligible. Domain not found. Assumed 0 retail."],
["c&c gamebridge","gamebridge.ca","1","1050000","Tabletop gaming","Eligible. 1 brand-owned store at 645 King St E Cambridge ON. 3000 sqft x $350/sqft."],
["Flower Lane","shopflowerlane.com","0","","Handmade crafts","Eligible. Online-only. No physical retail."],
["Wacky Riggers","wacky-riggers.myshopify.com","0","","Fishing tackle","Eligible. Online fishing gear. No brand-owned retail."],
["HiVis365 by Northeast Sign","www.hivis365.com","0","","Workwear/safety","Eligible. Online-only high-vis and PPE. No physical retail."],
["Mast Shoes","mastshoes.com","1","950000","Shoes","Eligible. 1 brand-owned store at 2519 Jackson Ave Ann Arbor MI. 2500 sqft x $380/sqft."],
["Quince Flowers","quinceflowers.com","1","700000","Florist","Eligible. 1 brand-owned florist at 20 Wagstaff Dr Toronto. 2000 sqft x $350/sqft."],
["Rusty Hinges Ranch","www.rustyhingesranch.com","1","375000","Farm market","Eligible. 1 farm market at 212 Chileno Valley Rd Petaluma CA. 1500 sqft x $250/sqft."],
["oncnaturalcolors.com","oncnaturalcolors.com","0","","Hair color","Eligible. Online D2C and B2B. No brand-owned retail."],
["Dream Weaver Canada","shopdreamweaver.ca","0","","Gifts/ethical retail","Eligible. Online-only. No physical retail."],
["MESS in a Bottle","www.messinabottle.com","0","","Apparel","Eligible. Online D2C. No brand-owned retail."],
["Luke's Lobster Wholesale","lukeslobster.myshopify.com","0","","Seafood","INELIGIBLE. Wholesale/B2B-only storefront."],
["LOST HUNT VINTAGE","losthuntvintage.com","0","","Vintage rugs","Eligible. Online-only. No physical retail."],
["Synchrony Private Label Shop","synchronyprivatelabel.com","0","","Financial services","INELIGIBLE. Credit card/financing. Not retail."],
["Declaration Grooming","www.declarationgrooming.com","0","","Wetshaving","Eligible. Online-only artisan shaving. No brand-owned retail."],
["Lopine","emryne.store","0","","Apparel","Eligible. Not clearly linked to physical retail. 0 locations."],
["Manafacture DTF","manadtf.com","0","","DTF printing","INELIGIBLE. B2B-only. Sells to shops and creators."],
["Minzuu","www.minzuu.com","0","","Global crafts","Eligible. Online-only artisan goods. No physical retail."],
["DecksGo","www.decksgo.ca","0","","Deck hardware","Eligible. Online-only. No physical retail."],
["Zeal","livezeal.com","0","","Supplements","Eligible. Online-only. No brand-owned retail."],
["Big River Hardware","bigriverhardware.com","0","","Hardware","Eligible. Domain not found. Assumed 0 retail."],
["Post Meridiem Spirits","shop.postmeridiemspirits.com","0","","Ready-to-drink cocktails","Eligible. Sold at liquor retailers. Atlanta pickup only. No brand-owned retail."],
["TO112","www.to112.com","0","","Unknown","Eligible. Domain not found. Assumed 0 retail."],
["Kasey Kahne","kaseykahne.com","0","","NASCAR merchandise","Eligible. Online-only. No brand-owned retail."],
["INARU","shopinaru.com","0","","Fashion","Eligible. Online-only. No physical retail."],
["Nomad1942","nomad1942.com","0","","Luxury cashmere","Eligible. Online-only. No physical retail."],
["CEOrganix","ceorganix.com","0","","Wellness supplements","Eligible. Online-only. No retail."],
["Plushology","plushology.com","0","","Plush toys","Eligible. Online retail division. No brand-owned physical retail."],
["7th Heaven Chocolate","www.7thheavenchocolate.com","0","","Chocolate","Eligible. Sold at Stop & Shop/Wegmans. No brand-owned retail."],
["Popular Woodworking","store.popularwoodworking.com","0","","Woodworking","Eligible. Online magazine store. No physical retail."],
["797 Offroad","797offroad.com","1","1200000","Off-road parts","Eligible. 1 brand-owned location at 2584 W Maple Ave Feasterville PA. 4000 sqft x $300/sqft."],
["Allen Stone","www.allenstone.com","0","","Musician merchandise","Eligible. Online-only. No brand-owned retail."],
["BBBrooke","shopbbbrooke.com","0","","Disney accessories","Eligible. Online-only. No physical retail."],
["The University of Science and Philosophy","philosophy-org.myshopify.com","1","320000","Educational/merchandise","Eligible. 1 museum/gallery at 1600 sqft in Waynesboro VA. 1600 sqft x $200/sqft."],
["Soul Coughing Store","soulcoughingstore.com","0","","Band merchandise","Eligible. Online-only. No brand-owned retail."],
["Aloha Hawaii Orchids","hiorchids.com","0","","Orchids","Eligible. Online orchid shipping. No physical retail."],
["SleepLikeABear.com","sleeplikeabear.com","0","","Sleep products","Eligible. Online-only. No physical retail."],
]

batch751=[
["MakeUpMania.com","www.makeupmania.com","1","1125000","Cosmetics","Eligible. 1 brand-owned retail Denver CO. 1x2500x450x1.0."],
["Tap N Roll","tapnrollva.com","1","800000","Trading card games","Eligible. 1 brand-owned retail Williamsburg VA. 1x2000x400x1.0."],
["NewVintageThrifts","newvintagethrifts.com","0","","Vintage clothing","Eligible. Online only. No brand-owned physical retail."],
["Public Myth Canada","shop.publicmyth.ca","1","700000","Sustainable activewear","Eligible. 1 Vancouver showroom. 1x2000x350x1.0."],
["FaceTory","www.facetory.com","0","","K-beauty skincare","Eligible. Online only. No brand-owned physical retail."],
["glazdjewels","glazdjewels.com","0","","Jewelry","Eligible. Online only. No brand-owned physical retail."],
["Catholic Data.Co","catholicdata.co","0","","Data products","INELIGIBLE. B2B-only. Parish/school database lists."],
["LionsLegacyClub","lionslegacyclub.com","0","","Unknown","Eligible. Domain unclear. No brand-owned retail found."],
["Muse Kits","musekits.com","0","","Art subscription kits","Eligible. Online subscription only. No brand-owned physical retail."],
["Merry Clinic","merryclinic.net","0","","Healthcare","Eligible. Medical clinic. No retail storefront found."],
["VintageWinter","www.vintagewinter.com","0","","Vintage winter sports decor","Eligible. Online only. No brand-owned physical retail."],
["Romans Jewelry","romansjewelry.com","2","3200000","Jewelry","Eligible. 2 brand-owned stores Folsom and Placerville CA. 2x2000x800x1.0."],
["Reed's Italian Dressing","www.reedsdressing.com","0","","Food condiments","Eligible. DTC and third-party retail only. No brand-owned stores."],
["Concierge Diamonds","conciergediamonds.com","1","1200000","Jewelry","Eligible. 1 LA showroom by appointment. 1x1500x800x1.0."],
["Picadilly Canada","us.picadilly.ca","1","875000","Women's fashion","Eligible. 1 Toronto store. 1x2500x350x1.0."],
["Mann's Jewelers","www.mannsjewelers.com","1","2400000","Jewelry","Eligible. 1 Rochester NY store. 1x3000x800x1.0."],
["Chefs' Toys ReOrder","reorderchefstoys.myshopify.com","0","","Restaurant supply","INELIGIBLE. Wholesale/B2B commercial kitchen equipment."],
["Billet Pro Shop Wholesale","b2b.billetproshop.com","0","","Automotive parts","INELIGIBLE. Wholesale/B2B-only."],
["Let's Get Crafty Customs","letsgetcraftycustoms.com","0","","Custom merchandise","Eligible. Online only. No brand-owned physical retail."],
["La-Reina Cosmetics","lareinacosmetics.com","0","","Cosmetics","Eligible. Online only. No brand-owned physical retail."],
["SheerGirl","www.sheergirl.com","0","","Formal wear dresses","Eligible. Online only. No brand-owned physical retail."],
["OnlyRawBeauty","www.onlyrawbeauty.com","0","","Hair products","Eligible. Online only. No brand-owned physical retail."],
["MPI Home Video","www.mpihomevideo.com","0","","DVD/Blu-ray","Eligible. Online and distribution. No consumer retail storefront."],
["BRAVON BEAUTY","bravonbeauty.com","0","","Professional makeup","Eligible. Online only. No brand-owned physical retail."],
["Bunny James Boxes","bunnyjamesboxes.com","0","","Snack subscription","Eligible. Online and corporate. No brand-owned physical retail."],
["agape candles wholesale","www.shopagapecandleswholesale.com","0","","Candles","INELIGIBLE. Wholesale-only. Password-protected B2B site."],
["Native Nectar Botanicals","nativenectarbotanicals.com","1","675000","Skincare and spa","Eligible. 1 Crested Butte retail and spa. 1x1500x450x1.0."],
["Paper Trail Rhinebeck","papertrailrhinebeck.com","1","500000","Stationery and gifts","Eligible. 1 Rhinebeck NY store. 1x2000x250x1.0."],
["Blake & Taylor Chalk Furniture Paint","blakeandtaylorpaint.com.au","0","","Furniture paint","Eligible. Australia online only. No brand-owned physical retail."],
["Great Lakes Proud","www.greatlakesproud.com","0","","Regional merchandise","Eligible. Online only. No brand-owned physical retail."],
["AliviOTC","storegoldkidney.myshopify.com","0","","Health supplements","Eligible. Opening soon. No brand-owned physical retail."],
["Aleppo Savon","alepposavon.ca","2","1080000","Soap and personal care","Eligible. 2 locations Calgary and West Edmonton Mall. 2x1500x300x1.2."],
["TB Publishing","tinybibles.com","0","","Religious books","Eligible. Online only. No brand-owned physical retail."],
["Wines from France","winesfromfrance.com","0","","Wine","Eligible. Online only. No brand-owned physical retail."],
["Adam Doleac Shop","adamdoleac.shop","0","","Music merchandise","Eligible. Online only. No brand-owned physical retail."],
["Sending You Aloha","sendingyoualoha.com","0","","Flowers and gifts","Eligible. Online and local delivery. No brand-owned physical retail."],
["Fairy Garden Store","fairygardenstore.com","0","","Miniature fairy garden","Eligible. Online only. No retail storefront."],
["Goddess Maintenance Company","goddessmaintenance.com","14","6300000","Haircare and nail salons","Eligible. 14 salon locations OH and IN. 14x1500x300x1.0."],
["Shop4Him","shop4him.com","1","600000","Men's gifts and gear","Eligible. 1 Lebanon TN store. 1x2000x300x1.0."],
["Unofive","unofive.ca","0","","Fitness equipment","Eligible. Online only. No physical retail stores."],
["Stay You Shop","stayyou.ca","0","","Apparel and books","Eligible. Online only. No brand-owned physical retail."],
["TourGear Designs","www.tourgeardesigns.com","0","","Audio cables","Eligible. Online and dealers. No brand-owned physical retail."],
["Jeff McWhinney Designs","mcwhinneydesigns.com","0","","Custom jewelry","Eligible. Mill Valley studio. Appointment-only. No walk-in retail."],
["Soulicious Vegan Kitchen","souliciousvegankitchen.com","1","900000","Vegan restaurant","Eligible. 1 Apopka FL restaurant. 1x1500x600x1.0."],
["The Headspace","theheadspace.net","1","350000","Streetwear and accessories","Eligible. 1 Denver store. 1x1000x350x1.0."],
["LumiLor","shop.lumilor.com","0","","Electroluminescent paint","Eligible. Sold via dealers. No brand-owned retail."],
["VIF Propeller","vifprop.com","0","","Boat propellers","INELIGIBLE. B2B/OEM wholesale manufacturer."],
["The Restaurant Authority","therestaurantauthority.com","0","","Commercial kitchen equipment","INELIGIBLE. B2B commercial kitchen wholesale."],
["shopmarketnet","shopmarketnet.com","0","","Unknown","Eligible. Domain unclear. No retail found."],
["Metals Farm","metalsfarm.ca","1","450000","Custom metalwork","Eligible. 1 Mississauga showroom. 1x1500x300x1.0."],
]

with open(output_file, 'a', newline='', encoding='utf-8') as f:
    writer = csv.writer(f)
    writer.writerows(batch601)
    writer.writerows(batch651)
    writer.writerows(batch701)
    writer.writerows(batch751)

total = len(batch601) + len(batch651) + len(batch701) + len(batch751)
print(f"Appended {total} rows")
