import csv

output_file = "/workspace/retail_location_validation_results.csv"

# Businesses 201-250
batch201 = [
["The Canada Popcorn Company","popcornmachine.ca","0","","Commercial popcorn equipment","Eligible. Commercial/home theater popcorn machines. No brand-owned retail locations; online/wholesale only."],
["Oak City Inline Skate Shop","oakcityskate.com","0","","Inline skates and accessories","Eligible. Warehouse-only (no walk-ins); excluded as retail."],
["Luxe Fashion","shopluxefashion.com","1","980000","Specialty apparel","Eligible. 1 store: 14234 SW 8th St Miami FL. Women's fashion. 1x1400x700x1.0."],
["Onekid","onekid.com","0","","Children's outerwear","Eligible. Car seat coats and baby gear. Online-only; no retail."],
["Chill-N-Reel","chillnreel.com","0","","Fishing beverage coolers","Eligible. Fishing-themed can coolers. Online-only; no retail."],
["Legator Guitars US","legatorguitars.com","0","","Guitars","Eligible. Office/showroom in Sun Valley CA; not public retail. Dealers only."],
["SlimSpaOnline","slimspaonline.com","0","","Body contouring products","Eligible. Topical slimming/beauty. No CBD/kratom. Online-only."],
["Hammerly Ceramics","www.hammerlyceramics.com","1","712500","Ceramics and pottery","Eligible. 1 studio/store: 8127 W 94th Ave Broomfield CO. 1x1500x475x1.0."],
["MyCozyBoots","mcozyboots.com","0","","Footwear","Eligible. Boots and shoes. Online-only; no retail."],
["Sud Factory","sudfactory.net","0","","Spot removers and cleaning","Eligible. Cleaning products. Online-only; no retail."],
["ETSpec.com","etspec.com","0","","European automotive parts","Eligible. Tuning/performance parts. Online-only; no retail."],
["The Midnight (US)","store-us.themidnightofficial.com","0","","Band merchandise","Eligible. Apparel and music. Online-only; no retail."],
["Organic Cotton Plus","organiccottonplus.com","0","","Organic fabric","Eligible. Fabric and textiles. Online-only; no retail."],
["Let's Roll Mobility","letsrollmobility.com","0","","Mobility aids","Eligible. Walkers and mobility. Online-only; no retail."],
["Recreations Outlet","recreationsoutlet.com","2","4750000","Outdoor play equipment","Eligible. 2 showrooms: Milford OH and Powell OH. 2x5000x475x1.0."],
["Home Improvement Supply","home-improvement-supply.myshopify.com","1","3800000","Furniture and home","Eligible. 1 store: 37754 W Red Arrow Hwy Paw Paw MI. 1x8000x475x1.0."],
["Atla Water","atlawater.com","0","","Water filtration systems","Eligible. Alkaline water systems. Online-only; no retail."],
["Onex Shoes","www.onexshoes.com","0","","Women's footwear","Eligible. Italian comfort shoes. Online-only; no retail."],
["Dermachom.com","dermachom.com","0","","Skincare","Eligible. Skincare. Online-only; limited public info."],
["Vela Vici","velavici.com","0","","Fashion/accessories","Eligible. Limited info; likely online-only."],
["Pure Over","pureover.com","0","","Glass coffee equipment","Eligible. Brew kits and drinkware. Online-only; no retail."],
["Lazer Ladies","www.lazerladies.com","1","1500000","Custom gifts and awards","Eligible. 1 store: 2543 E Washburn Rd North Las Vegas NV. 1x3000x500x1.0."],
["Ojais Wellness","www.ojaiswellness.com","0","","Wellness supplements","Eligible. Supplements and wellness. Online-only; no retail."],
["Luke's Locker Running & Fitness","lukeslocker.com","2","4350000","Running and fitness","Eligible. 2 stores: Dallas TX and Fort Worth TX. 2x3000x725x1.0."],
["CompoCloset","compocloset.com","0","","Composting toilets","Eligible. Off-grid toilets. Online-only; no retail."],
["medicrunch","www.medicrunch.com","0","","Pet medication aids","Eligible. Pet pill treats. Online-only; no retail."],
["August Burns Red Official Store","augustburnsredtourmerch.com","0","","Band merchandise","Eligible. Apparel and music. Online-only; no retail."],
["Pride of Bristol Bay","prideofbristolbay.com","0","","Wild Alaskan salmon","Eligible. Seafood DTC. Pickup points only; no brand-owned retail."],
["Coco & Rho","www.cocoandrho.com","0","","Hats and apparel","Eligible. Trucker hats and sweatshirts. Online-only; no retail."],
["Secured Tech","shop.securedtech.com","0","","K-12 device solutions","INELIGIBLE. B2B/wholesale only for K-12 school districts."],
["Little Ouchies","littleouchies.com","0","","Sensory tools","Eligible. Grippies and Spikies. Online-only; no retail."],
["LUMINOUS COFFEE","www.loveluminous.coffee","0","","Specialty coffee","Eligible. Small-batch coffee. Online-only; no retail."],
["Noor Jouels","www.noorjouel.com","0","","Luxury jewelry","Eligible. Lab-grown diamond jewelry. Online-only; no retail."],
["LESSE","lesseofficial.com","0","","Clean skincare","Eligible. Skincare. Online-only; sold via stockists."],
["Made on Jupiter","madeonjupiterleatherlab.com","0","","Leather crafting supplies","Eligible. Leather and tools. Online-only; no retail."],
["ZeroSportsDepot.com","zerosportsdepot.com","0","","Shooting sports gear","INELIGIBLE. Firearms/ammunition; competitive shooting proshop."],
["Westheffer","westheffer.com","0","","Unknown","Eligible. Limited info; likely online-only."],
["Revival Marine Care","www.shoprevivalmarinecare.com","0","","Boat detailing products","Eligible. Marine care. Mobile detailing only; no retail storefront."],
["Tarps & Tie-Downs","tarpstiedowns.com","1","2500000","Tarps and cargo control","Eligible. 1 store: 945 E Lindsay St Stockton CA. 1x5000x500x1.0."],
["Paper and Supply","paperandsupply.com","0","","Business paper products","Eligible. Carbonless paper and office supplies. Online-only; no retail."],
["PartsNet","partsnet.ca","0","","Appliance parts","Eligible. Appliance repair parts. Online-only; no retail."],
["KUANIA","kuania.com","0","","Oro laminado jewelry","INELIGIBLE. Wholesale/B2B-only; minimum order $100."],
["Raingler","raingler.com","0","","Vehicle cargo nets","Eligible. Jeep/vehicle nets. Online-only; no retail."],
["Wook Books Coloring","wookbooks.com","0","","Coloring books","Eligible. Coloring books and markers. Online-only; no retail."],
["Carbon Showroom","carbonshowroom.com","0","","Carbon fiber auto parts","Eligible. Automotive parts. Online-only; no retail."],
["Montana Gift Corral","www.giftcorral.com","5","6000000","Montana gifts and souvenirs","Eligible. 5 stores: Bozeman Missoula airport Lewis & Clark Caverns. 5x2000x500x1.2."],
["Belyser","belyser-shop.com","0","","Unknown","Eligible. Limited info; likely online-only."],
["Okra & Molly","okraandmolly.com","0","","Unknown","Eligible. Limited info; likely online-only."],
["brooksienaturals","shopbrooksie.com","0","","Natural skincare","Eligible. Handcrafted skincare. Online-only; no retail."],
["hammy3dprints","hammy3dprints.com","0","","3D-printed mounts","INELIGIBLE. Firearm magazine and gun mounts."],
]

# Businesses 251-300
batch251 = [
["ArtEast Studio","members.arteaststudio.net","0","","Online dance and arts studio","No brand-owned retail locations; online classes and media only."],
["Rework Office Furniture","rework-furniture.com","1","812500","Office furniture - new and used","1 showroom at 905 S Menard Ave Chicago IL; 9AM-4PM M-F; ~2500 sqft x $325/sqft x 1.0."],
["ELAC America","elac-america.myshopify.com","0","","Speakers and audio equipment","Online only; sells via dealer network; no brand-owned retail."],
["ecustomrim","www.ecustomrim.com","0","","Trailer tires wheels and accessories","Online only; no physical retail locations."],
["Meadowbrooke Gourds","www.mbgourds.com","1","1750000","Hand-crafted gourds and gift shop","1 retail at 125 Potato Rd Carlisle PA; 7000 sqft gift shop; 10AM-5PM; ~7000 x $250 x 1.0."],
["IIID MAX","iiidmax.com","0","","3D printing filament","Online only; Miami-based manufacturer; no retail locations."],
["True Seal Gaskets","www.truesealgaskets.com","0","","Commercial refrigeration gaskets","INELIGIBLE - B2B/wholesale only; commercial refrigeration supplies."],
["Oxford Street - BayFair","shopoxfordstreet.com","1","975000","Men's and children's apparel","1 store at Bayfair Center 15555 E 14th St San Leandro CA; mall retail; ~3000 x $325 x 1.0."],
["QuiltwithMissKate","www.quiltwithmisskate.com","0","","Quilting fabric and supplies","Online only; launched 2024; no physical retail."],
["RPFILMS","rpwindowfilms.com","0","","Window tint and paint protection film","Online with in-store pickup; no confirmed public retail store; warehouse pickup only."],
["Rip Van","www.ripvan.com","0","","Low-sugar snacks and wafels","DTC brand sold at retailers; no brand-owned retail locations."],
["LILLEbaby","www.lillebaby.com","0","","Baby carriers and wraps","Online only; sells via authorized dealer network; no brand-owned stores."],
["All Three","www.allthreestudio.com","0","","Art/design studio","Website could not be verified; no retail location information found."],
["Preaux Tuning","www.preauxtuning.com","0","","Ford vehicle tuning and performance parts","Online only; no physical retail locations."],
["the cutting garden","www.mycuttinggarden.com","0","","Flowers/garden","Website could not be verified; no retail location information found."],
["Extreme Wellness Supply","extremewellnesssupply.com","0","","Juicers blenders dehydrators","Online only; kitchen appliances; no physical retail."],
["Kent Custom Cases","kentcustom.com","1","650000","Custom road cases for music/AV","1 showroom at 298 Hinman Ave Buffalo NY; 9AM-6PM M-F; ~2000 sqft x $325 x 1.0."],
["WLO Store","wlostore.com","0","","Luxury pet furniture","Online only; no physical retail locations."],
["VitalForge","vitalforgemd.com","0","","Medical wellness clinic","Medical clinic; not retail; product sales tied to clinical services."],
["McIntosh Laboratory Inc.","shop.mcintoshlabs.com","1","3575000","High-end audio equipment","1 House of Sound NYC 357 W 17th St; 11000 sqft; ~11000 x $325 x 1.0."],
["Mammoth","mammoth.band","0","","Band merchandise and music","Online merch; no brand-owned retail locations."],
["Plastic Products Mfg.","plasticproductsmfg.com","0","","Acrylic display and signage","Online only; Yorba Linda; no retail store; B2B/manufacturer."],
["Nomad-Design-International","www.nomadtackle.com.au","0","","Fishing tackle - Australia","Australia-based; no US retail locations found."],
["Ground Score","mygroundscore.com","0","","Unverified","Website could not be verified; no retail location information found."],
["AccessDivision","accessdivision.com","0","","Garage and automotive equipment","Online only; no physical retail locations."],
["Flagshipgifts","flagshipgifts.com","0","","Promotional and corporate gifts","Online/promotional; no brand-owned retail locations found."],
["Elements by Remedy","elementsbyremedy.com","0","","Supplements","Website could not be verified; no retail location information found."],
["Purely Relaxation","www.purelyrelaxation.com","0","","Saunas massage chairs","Online only; no physical retail locations."],
["38 Motorsports LLC","38motorsports.com","0","","ATV performance parts","Online only; no physical retail locations."],
["Concept 841","concept841.com","0","","Unverified","Website search failed; no retail location information found."],
["All Star CNC Products Inc","store.allstarcnc.com","0","","CNC vacuum gaskets and tooling","INELIGIBLE - B2B/wholesale only; industrial CNC supplies."],
["Hi Power Cycles","hpcbikes.com","0","","Electric bikes","Website search failed; no retail location information found."],
["Lyricalhair","lyricalhair.com","0","","Hair replacement systems","Online only; South El Monte warehouse; no customer-facing retail."],
["Oneway77JC","oneway77jc.com","0","","Unverified","Website could not be verified; no retail location information found."],
["StableFeed","stablefeed.com","0","","Horse feed and supplements","Online and distributors; no brand-owned retail locations."],
["Fabli","fabli.co","0","","Unverified","Website could not be verified; no retail location information found."],
["Eagle Bounce","eaglebounce.com","1","650000","Commercial inflatables","1 location at 407 113th St Arlington TX; showroom/warehouse; ~2000 sqft x $325 x 1.0."],
["Franklin BBQ Pits","franklinbbqpits.com","0","","BBQ smokers and pits","Online and dealers; no brand-owned retail locations."],
["Pc Room","thepcroom.com","1","487500","Refurbished computers and repair","1 physical location 546 Gladstone Ave Ottawa ON; 10AM-6PM; ~1500 sqft x $325 x 1.0."],
["Clevens Face and Body Specialists","shop.drclevens.com","1","975000","Medical-grade skincare","Retail at clinic; Melbourne FL 707 W Eau Gallie Blvd; ~3000 sqft x $325 x 1.0."],
["Hotel Emma","shop.thehotelemma.com","1","812500","Luxury gift shop","1 Curio boutique at 136 E Grayson St San Antonio TX; 9AM-8PM; ~2500 sqft x $325 x 1.0."],
["Riverboat Discovery","shopify.riverboatdiscovery.com","1","650000","Alaska souvenirs and gift shop","1 gift shop at 1975 Discovery Dr Fairbanks AK; tour attraction; ~2000 sqft x $325 x 1.0."],
["Garden Tool Company","www.gardentoolcompany.com","0","","Garden tools","Online only; no physical retail locations."],
["Bushere & Son Iron Studio Inc.","bushereandson.com","0","","Wrought iron hardware and decor","Online only; studio not open to public for pickup."],
["Avatar Merch USA","usa.avatarmetal.com","0","","Band merchandise","Online only; Nashville fulfillment; no brand-owned retail."],
["PurelyWHITE DELUXE","purelywhitedeluxe.com","0","","Teeth whitening products","Online only; no physical retail locations."],
["STEP 22 Gear","step22gear.com","0","","Adventure travel gear","Online only; no physical retail locations."],
["BassBoatWired.com","www.bassboatwired.com","0","","Marine electronics and bass boat accessories","Online only; DFW installation service; no retail store."],
["Austin Flower Delivery","austinflowerdelivery.com","1","812500","Florist - flowers and arrangements","1 retail at 11215 Research Blvd Austin TX; 8AM-3PM weekdays; ~2500 sqft x $325 x 1.0."],
["Whale Pod Shipper","whalepodshipper.com","0","","Beverage shipping packaging","INELIGIBLE - B2B/wholesale only; sells to beverage companies."],
]

# Businesses 301-350
batch301 = [
["JAENEA","jaenea.com","0","","Unknown","Website not found or unindexed; cannot verify products or retail presence."],
["I AM LEADER","iamleader.com","0","","Leadership books and training","Eligible products. No brand-owned physical retail locations found; online/digital only."],
["BIM","biminter.com","0","","B2B software/services","BIM platform for AEC professionals; B2B/wholesale-only; no consumer retail."],
["Ecoslay Wholesale","ecoslay-wholesale.com","0","","Hair care","INELIGIBLE: Wholesale/B2B-only in business name."],
["OKTAGON","oktagon-shop.com","0","","MMA apparel and merchandise","Eligible products. No brand-owned retail; sold via dealers/online."],
["Redwoods Pro Installer Store","redwoods.lighting","0","","Landscape lighting","INELIGIBLE: Pro installer/B2B-only; no consumer retail."],
["Double Cross Clothing Co.","doublecrossclothingco.com","0","","Apparel","Eligible graphic apparel. Online-only; no brand-owned retail."],
["Mara Pro","shop.marapmu.com","0","","Permanent makeup supplies","Eligible PMU products. Online-only; no brand-owned retail."],
["The DB Method","thedbmethod.com","0","","Fitness equipment","Eligible squat machine. Online-only; no brand-owned retail."],
["wholesomenova","wholesomenova.com","0","","Farm products and ice cream","Eligible farm goods. Online/farm sales; no brand-owned retail storefront."],
["The Silent Rider","atvsilencer.com","0","","ATV/UTV exhaust silencers","Eligible aftermarket parts. Online-only; no brand-owned retail."],
["Remonte Shoes","remonte.us","0","","Women's footwear","Eligible shoes. Online-only; no brand-owned retail."],
["The Old Man's Garage","theoldmansgarage.shop","0","","Apparel and merchandise","Eligible apparel. Online-only; no brand-owned retail."],
["Dave's Boots","www.davesboots.com","1","525000","Western and work boots","1 brand-owned store in Red Bluff CA. Est: 1x1500x350x1.0."],
["Pro Special Hardwood","pros.specialhardwood.com","0","","Wood finishing products","INELIGIBLE: Pro/contractor B2B-only."],
["J. Lee Bag Co.","www.jleebagco.com","0","","Custom paper bags","INELIGIBLE: B2B custom packaging; no consumer retail."],
["Honey Bee","honeybeez.com","0","","Skincare and cosmetics","Eligible honey-based skincare. Online-only; no brand-owned retail."],
["EuropeanBronze","www.europeanbronze.com","0","","Bronze sculptures and decor","Eligible bronze products. Online-only; no brand-owned retail."],
["VANPOWERS LTD","www.vanpowers.com","0","","E-bikes","Eligible e-bikes. Dealer network only; HQ not open to public; no brand-owned retail."],
["theMacroLAB","the-macrolab.com","0","","Supplements","Eligible supplements. Online-only; no brand-owned retail."],
["Z. Cioccolato","zcioccolato.com","1","675000","Artisan chocolate and fudge","1 brand-owned store in San Francisco. Est: 1x1500x450x1.0."],
["AGED IVY","agedivy.com","0","","Vintage and curated apparel","Eligible vintage clothing. Online-only; no brand-owned retail."],
["Vitruvin Longevity Supplements","www.vitruvin.com","0","","Longevity supplements","Eligible supplements. Online-only; no brand-owned retail."],
["Glamabayasss","glamabayasss.com","0","","Modest wear and abayas","Eligible apparel. Online-only; no brand-owned retail."],
["Arcades Market","arcadesmarket.com","1","600000","Arcade games and equipment","1 brand-owned store in St. Louis MO. Est: 1x1500x400x1.0."],
["Automatic Waterer Parts","www.automaticwatererparts.com","0","","Livestock waterer parts","Eligible farm parts. Warehouse-only; no retail storefront."],
["Vancouver Baskets","vancouverbaskets.ca","0","","Gift baskets","Eligible gift baskets. Delivery/online; no brand-owned retail storefront."],
["Roar Organic","roarorganic.com","0","","Hydration beverages","Eligible beverages. Sold at third-party retail; no brand-owned stores."],
["Blueprint CoC","blueprintcoc.com","0","","Clash of Clans base designs","Eligible digital coaching/design. Online-only; no physical retail."],
["HKP Tuning & Performance","www.hkptuning.com","0","","Performance car parts","Eligible aftermarket parts. Online-only; no brand-owned retail."],
["Smoky Mountain General Store","smgeneralstore.com","1","525000","General store and gifts","1 brand-owned store in Pigeon Forge TN. Est: 1x1500x350x1.0."],
["CoolBreeze Beverages","shop.coolbreezebeverages.com","0","","Frozen beverage mixes","Eligible beverage products. B2B-focused; no brand-owned retail."],
["Kinetic Society LLC","www.kineticsociety.com","0","","Custom Greek-life jerseys","Eligible apparel. Online-only; no brand-owned retail."],
["thesailwarehouse","thesailwarehouse.com","0","","Sailboat sails and canvas","Eligible sailing products. Online-only; no brand-owned retail."],
["Dermaesthetics For Professionals","pro.dermaestheticsusa.com","0","","Professional skincare","INELIGIBLE: B2B/professional-only; no consumer retail."],
["Combat Textiles","www.combattextiles.com","0","","Firearm and weapon wraps","INELIGIBLE: Firearms/weapons accessories."],
["Zero Fitness US","zerofitness.us","1","487500","Fitness equipment","1 showroom in South Gate CA (by appointment). Est: 1x1500x325x1.0."],
["SwissKubik","swisskubikus.com","0","","Watch winders","Eligible watch accessories. Online-only; no brand-owned retail."],
["Plug N Play Kits","plugnplaykits.com","0","","Automotive remote start kits","Eligible automotive kits. Online-only; no brand-owned retail."],
["Active Source Lab","active-source-lab.myshopify.com","0","","Supplements","Eligible supplements. Online-only; no brand-owned retail."],
["StretchyScreens","stretchyscreens.com","0","","Projection screens and displays","Eligible AV products. Online-only; no brand-owned retail."],
["Hope Innovations","hopeinnovation.ca","0","","Unknown","Website under construction; cannot verify."],
["Captain Chucks Flavor Island","www.captainchucksflavorisland.com","0","","E-liquid and vaping","INELIGIBLE: Tobacco/vaping products."],
["Herb's Fortune","www.herbsfortune.com","0","","Sunrider herbal supplements","Eligible herbal products. Online-only; no brand-owned retail."],
["We Fight Monsters","wefightmonsters.org","0","","Nonprofit apparel and merchandise","Eligible mission apparel. Online-only; no brand-owned retail."],
["Isalis","www.shopisalis.com","5","2437500","Women's apparel and accessories","5 brand-owned stores (3 SF 2 NY). Est: 5x1500x325x1.0."],
["AeroForce Technology Inc.","aeroforcetech.com","0","","OBD2 gauges and sensors","Eligible automotive diagnostics. Online-only; no brand-owned retail."],
["Annual Ornaments","www.annualornaments.com","0","","Christmas ornaments","Eligible ornaments. Online-only; no brand-owned retail."],
["Ollie's Day","olliesday.com","0","","Children's clothing","Eligible kids apparel. Online-only; no brand-owned retail."],
["Coconut Pops","www.coconutpops.com","0","","Children's clothing","Eligible kids apparel. Online-only; closing sale; no brand-owned retail."],
]

# Businesses 351-400
batch351 = [
["Everly Made","everlymade.com","0","","Jewelry","Online-only jewelry retailer. No brand-owned physical retail locations."],
["Stella & Tide","stellatide.com","0","","Catholic Jewelry","Online-only Catholic jewelry. No brand-owned physical retail locations."],
["FLYING MONKEY","flyingmonkeyjeans.com","0","","Apparel/Denim","Industry-only wholesale showroom in LA Fashion District. No consumer retail locations."],
["Dakota Dirt","dakotadirtcoffee.com","1","900000","Coffee","Brand-owned roasting facility with drive-through in Milnor ND. 1x1500x600x1."],
["Acuity RF","www.acuityrf.com","0","","Wi-Fi Technology","INELIGIBLE: B2B/wholesale-only enterprise Wi-Fi solutions."],
["The Annoying Present","theannoyingpresent.com","0","","Novelty Gifts","Online-only novelty gift product. No brand-owned physical retail."],
["Pick It Fence","pickitfence.com","1","375000","Gift Shop","Brand-owned gift shop at 190 Raglan St Renfrew ON. 1x1500x250x1."],
["MossArtInstallations","mossartinstallations.com","0","","Moss Art/Home Decor","Online-only moss art installations. No brand-owned physical retail."],
["Rough House Pictures Inc.","roughhouseshop.com","0","","Entertainment Merchandise","Online-only pop culture merchandise. No brand-owned physical retail."],
["Northern Lights Instruments","www.northernlightsinstruments.com","0","","Night Vision Equipment","Online-only night vision retailer. No brand-owned physical retail."],
["Hemloya","hemloya.com","0","","Unknown","Unable to verify business. No retail information found."],
["ProMeth","prometh.com","0","","Automotive Parts","Online-only water methanol injection systems. No brand-owned physical retail."],
["Oli&Carol US","oliandcarol.us","0","","Baby Toys","Online-only sustainable baby toys. No brand-owned physical retail."],
["Blacksmith Bolt & Rivet Supply","blacksmithbolt.com","0","","Hardware/Fasteners","Online-only fastener retailer. Portland office/warehouse only."],
["JidoriHome","jidorihome.myshopify.com","0","","Unknown","Limited information. Shopify store. No retail locations found."],
["Grace DTF Transfers","gracetransfers.com","0","","DTF Transfers","Online DTF transfer printing. Serves print shops. No brand-owned physical retail."],
["Ellza","ellza.ca","0","","Period/Leak-Proof Underwear","Online-only period panties. No brand-owned physical retail."],
["L A R K","www.larklarkgoose.com","0","","Unknown","Domain not found in search results. Unable to verify."],
["High Top Capes LTD","www.hightopcapes.com","0","","Barber Capes","Online-only barber capes. No brand-owned physical retail."],
["Better Bones Better Body","shop.betterbones.com","0","","Bone Health Supplements","Online-only bone health products. No brand-owned physical retail."],
["AIC Replacement Parts","www.aicreplacementparts.com","0","","Equipment Parts","INELIGIBLE: Wholesale/B2B-only replacement parts supplier."],
["VULGUS365","www.vulgus365.com","0","","Unknown","Website not found or unindexed. Unable to verify."],
["Mountain Fire Wheels","www.mountainfirewheels.com","0","","Auto Wheels/Tires","Online-only wheels and tires. Wylie TX. No brand-owned retail storefront."],
["Robert W. Stolz","www.robertwstolz.com","0","","Wool Clothing","Online-only European wool clothing. SC warehouse. No brand-owned retail."],
["Vidirlighting","vidirlighting.com","0","","Lighting Fixtures","Online-only lighting retailer. No brand-owned physical retail."],
["Bernina Jeff","bernina-jeff.myshopify.com","0","","Sewing Accessories","Online-only Bernina accessories. Grand Junction dealer. No brand-owned retail storefront."],
["Tennis Spectrum","shop.tennisspectrum.com","0","","Tennis Equipment","Online-only tennis retailer. No brand-owned physical retail."],
["Warriors & Scholars","warriorsandscholars.com","0","","Men's Apparel","Online-only comfort apparel. No brand-owned physical retail."],
["Meridian Boutique","www.meridianboutique.com","0","","Unknown","Limited information. No retail locations found."],
["Jamie Wolf","jamiewolf.com","0","","Luxury Jewelry","Online-only jewelry. NYC studio. No retail storefront."],
["The Slay Collection","slayedbydalvi.com","0","","Hair/Wigs","Online-only hair/wig brand. No brand-owned physical retail."],
["Core ProMed Supplies","corepromed.com","0","","Medical Supplies","Online-only medical supplies. B2B/insurance. No retail storefront."],
["Stacker2","www.stacker2.com","0","","Diet/Energy Supplements","Online-only supplement brand. No brand-owned physical retail."],
["High Monk","highmonkkratom.com","0","","Kratom","INELIGIBLE: Kratom products."],
["Sump Saver","shop.sumpsaver.com","0","","Agricultural Equipment","B2B grain bin equipment. No brand-owned retail."],
["Todoshop","www.todoshop.co.il","0","","Unknown","Israeli domain. Limited information. Unable to verify."],
["Avocado Toast","www.avocadotoastca.com","0","","Grocery Delivery","Online delivery service. No physical retail storefront."],
["Joseph's Organic Bakery","josephsorganicbakery.com","1","525000","Bakery","Brand-owned bakery at 18228 W Dixie Hwy North Miami Beach FL. 1x1500x350x1."],
["Albrecht Jewelry","albrechtjewelry.com","0","","Custom Jewelry","Online-only custom jewelry. No retailer storefront."],
["Play Pits","play-pits.myshopify.com","0","","Unknown","Limited information. Shopify store. No retail found."],
["Kase Custom","kasecustom.com","0","","Reclaimed Wood Furniture","Online-only custom furniture. Arizona. No brand-owned retail."],
["Anthony Marinelli Music LLC","anthonymarinellimusic.com","0","","Music/Merchandise","Online-only music shop. No brand-owned physical retail."],
["Bennett To The Trade","www.bennetttothetrade.com","0","","Furniture","INELIGIBLE: Trade-only furniture. B2B interior designers."],
["Made by Nuwa","madebynuwa.com","0","","Unknown","Domain not clearly indexed. No retail information found."],
["K Kane","k-kane.com","0","","Fine Jewelry","Online-only fine jewelry. NYC. No brand-owned retail."],
["ShredLights","shredlights.com","0","","LED Lights","Online-only sports lighting. No brand-owned physical retail."],
["JAYBOYMODZ","jayboymodz.com","0","","Retro Gaming Mods","Online-only custom Game Boy mods. No brand-owned physical retail."],
["The BRAND Label","www.thebrand-label.com","0","","Fashion","Online-only fashion retailer. No brand-owned physical retail."],
["Livom","livom.ca","0","","Unknown","Domain not found in search. Unable to verify."],
["Luminous Tints","shopluminous.com","0","","Window Tints","Online wholesale/installer. No brand-owned retail storefront."],
]

with open(output_file, 'a', newline='', encoding='utf-8') as f:
    writer = csv.writer(f)
    writer.writerows(batch201)
    writer.writerows(batch251)
    writer.writerows(batch301)
    writer.writerows(batch351)

total = len(batch201) + len(batch251) + len(batch301) + len(batch351)
print(f"Appended {total} rows to {output_file}")
