import csv, io
output_file = "/workspace/retail_location_validation_results.csv"

# Parse CSV data from agent outputs, standardizing format
raw_data = """Petaluma Pie,petalumapiecompany.com,1,180000,Bakery/Pies,"Eligible. 1 brand-owned bakery cafe at 125 Petaluma Blvd N Petaluma CA. 1x1200x150."
Hello To Natural LLC,www.hellotonatural.com,0,,Natural Skincare,"Eligible. Online-only. No physical retail."
Mike the Mattress Guy,www.shopmikethemattressguy.com,1,240000,Mattresses/Furniture,"Eligible. 1 retail at 555 Mapleview Dr W Barrie ON."
Figgyduff Dory,www.figgyduffdory.com,0,,Apparel/Gifts,"Eligible. Online-only Newfoundland-themed apparel."
Fortune Honey,fortunehoney.com,0,,Honey/Food,"Eligible. Online-only. No physical retail."
Inklings Paperie,inklingspaperie.com,0,,Paper Goods,"Eligible. Sold through 2000+ stockists. No brand-owned retail."
Headwaters Outfitters,shopheadwatersoutdoors.com,1,150000,Outdoor Gear,"Eligible. 1 store at 25 Parkway Rd Rosman NC."
Spring Loaded,spring-loaded-ca.myshopify.com,0,,Unknown,"Eligible. Shopify store. No physical retail."
OhYasFit,ohyasfit.com,0,,Fitness Apparel,"Eligible. Online-only. No physical retail."
MCHARMS,mcharms.com,0,,Jewelry,"Eligible. Online-only handmade jewelry. No physical retail."
Parfumelle,perfumelle-store.myshopify.com,1,300000,Perfume/Fragrance,"Eligible. 1 store at 7411 Hines Place Dallas TX."
Ye Ole Sweet Shoppe,yeolesweets.com,1,200000,Bakery/Sweets,"Eligible. 1 retail at 402 State St Erie PA."
FireSide Food Shop,firesidefoodshop.com,0,,Prepared Foods,"Eligible. Online ordering with delivery. No walk-in retail."
TRIPLE D DODI'S DIPS AND DECALS,triple-d-dodi-s-dips-and-decals.myshopify.com,0,,Nail Products,"Eligible. Online-only. No physical retail."
Diamond Legends Online,diamondlegends.com,0,,Unknown,"Eligible. Domain not clearly identified. No physical retail."
JLF Adventures,www.jlfadventures.com,0,,Paddle Boards,"Eligible. Online-only. Office/warehouse only."
Perfect Baskets,www.perfectbaskets.ca,0,,Gift Baskets,"Eligible. Toronto-based online gift shop. No physical retail."
Sarkis Pastry,sarkispastry.com,3,540000,Middle Eastern Pastries,"Eligible. 3 locations: Glendale, Pasadena, Anaheim CA."
Razorglove.com,razorglove-com.myshopify.com,0,,Shaving/Razor,"Eligible. Shopify store. No physical retail."
Brooklyn Equipment,brooklyn-equipment.com,1,180000,Equipment/Tools,"Eligible. 1 location at 983 Dean St Brooklyn NY."
The House of Stylez,thehouseofstylez.com,0,,Women's Apparel,"Eligible. Online-only. No physical retail."
Invicta Jewelry,invictajewelry.com,3,900000,Jewelry/Watches,"Eligible. 3+ stores: Sawgrass FL, Woodbridge NJ, Orlando FL."
QD Jewelry,qdjewelers.com,0,,Luxury Jewelry,"Eligible. Online luxury watch and jewelry buyer. No consumer retail."
Snow's Boutique,snowsboutique.com,0,,Gift/Napkins,"Eligible. Canadian online gift shop. No physical retail."
Kincaid's Is Music,www.kincaidsmusic.com,1,350000,Music Instruments,"Eligible. 1 retail at 1325 W 1st St Springfield OH."
Greek Wellness,www.greekwellness.com,0,,Supplements,"Eligible. Online-only. No physical retail."
Betty Beauty,www.bettybeauty.com,0,,Beauty/Coloring,"Eligible. Online-only. No physical retail."
Downtown Deco,downtowndeco.com,1,180000,Gift Shop,"Eligible. DECO Raleigh at 207 S Salisbury St. 1 physical store."
muslimquiz,www.muslimquiz.de,0,,Islamic Education,"Eligible. Islamic quiz app. No physical retail."
Salt & Gold Collection,www.saltandgold.com.au,0,,Art/Prints,"Eligible. Australian online art prints. No physical retail."
Dusti Rhoads,dustirhoadswholesale.com,0,,Western Accessories,"INELIGIBLE. Wholesale/B2B-only."
Laidrey Coffee Roasters,www.laidrey.com,3,450000,Coffee/Cafe,"Eligible. 3 cafes: Tarzana, Encino, Agoura Hills CA."
Myrtle Greens,myrtlegreens.com,0,,Unknown,"Eligible. No physical retail found."
Preval,store.preval.com,0,,Paint Sprayers,"Eligible. Online store. Sold at Home Depot. No Preval-owned retail."
Winning Streak,winningstreakathletics.com,1,250000,Sports Memorabilia,"Eligible. 1 location at 7700 I-70 Frontage Rd Columbia MO."
ONEINMIL,www.oneinmil.com,0,,Unknown,"Eligible. No physical retail found."
Custard Boutique,custardboutique.com,0,,Unknown,"Eligible. No physical retail found."
Food Huggers DS,food-huggers-drop.myshopify.com,0,,Food Storage,"Eligible. Online-only. No physical retail."
House of Lucky,www.houseoflucky.com,0,,Jewelry/Gaming,"INELIGIBLE. Domain associated with gambling platform."
TossSauce,www.shoptosssauce.com,0,,Sauce/Apparel,"Eligible. Online-only. No physical retail."
Alyce Paris,alyceparis.com,0,,Prom Dresses,"Eligible. Online and wholesale to retailers. No brand-owned retail."
Eclipse Glasses,www.eclipseglasses.com,0,,Eclipse Glasses,"Eligible. B2B/wholesale primary. No permanent retail."
Miss-me-art,missmeart.com,0,,Art/Prints,"Eligible. Online-only. No physical retail."
STEELWITHTEETH,steelwithteeth.com,0,,Unknown,"Eligible. No physical retail found."
Keyless2Go,keyless2go.com,0,,Car Keys,"Eligible. Online replacement car keys. No physical retail."
K-Sense,k-sense.shop,0,,Unknown,"Eligible. No physical retail found."
Sports Officiating Supplies,sportsofficiatingsupplies.com,0,,Officiating Apparel,"Eligible. Online-only. No physical retail."
BoutiqueLL,boutiquelbismarck.com,1,120000,Women's Apparel,"Eligible. 1 store at 1001 W Interstate Ave Bismarck ND."
Hadley Olivia Mattress Superstore,www.hadleyolivia.com,1,400000,Mattresses,"Eligible. 1 showroom at 31896 Plaza Dr San Juan Capistrano CA."
PrintandSwag,printandswag.com,0,,Custom Apparel,"Eligible. Print-on-demand. No physical retail."
the sclpt co,thesclptco.com,0,,Skincare,"Eligible. DTC skincare. No brand-owned physical retail."
EIGHT,iwear8.com,0,,Sunglasses/Apparel,"Eligible. Sells through authorized retailers only; no brand-owned stores."
Art & SoulWorks,art-soulworks.com,0,,Faith-based Gifts,"Eligible. Online only; wholesale to retailers."
Nossos Brazileirinhos,www.nossosbrazileirinhos.com,0,,E-commerce,"Eligible. Brazilian e-commerce. No physical retail."
Elly and Grace Wholesale,wholesale.ellyandgrace.com,0,,Christian Apparel,"INELIGIBLE. Wholesale/B2B-only."
Mudology,mudology.com,0,,Skincare,"Eligible. Canadian clay face masks. DTC online only."
Dean accessories,deanaccessories.net,0,,Leather Goods,"Eligible. LA-based online retailer."
ToothScience,www.toothscience.com,0,,Oral Care,"Eligible. Online and dental offices; no brand-owned retail."
That's it. Wholesale,wholesale.thatsitfruit.com,0,,Snack Bars,"INELIGIBLE. Wholesale/B2B-only."
Bob's Fight Shop,bobsfightshop.com,0,,Boxing/MMA Gear,"Eligible. Canada online only; no physical store."
Home + Home,homeplushome.com,0,,Home Decor,"Eligible. Online only."
Step 'N Style,www.snsnola.com,1,400000,Men's Fashion,"Eligible. 1 store in New Orleans. 1x2000x200."
Modern Rebel Boutique,modernrebelboutique.com,1,300000,Women's Apparel,"Eligible. 1 store in Oak Grove MN."
Oxa Leather,oxaleather.com,0,,Leather Accessories,"Eligible. DTC online only."
Food Huggers Wholesale,food-huggers-wholesale.myshopify.com,0,,Food Storage,"INELIGIBLE. Wholesale/B2B-only."
The Perfume Club,perfumeclub.com,0,,Fragrance,"Eligible. Online only."
JAY BONADIO,jaybonadio.com,0,,Jewelry/Fashion,"Eligible. No physical stores found."
NOVA VITA,solutions4.myshopify.com,0,,Supplements,"Eligible. Online only."
PrideBooth,pridebooth.com,0,,LGBTQ+ Apparel,"Eligible. Online only."
Little Unicorn B2B Canada,canadawholesale.littleunicorn.com,0,,Baby Products,"INELIGIBLE. Wholesale/B2B-only."
Gregorian Rugs,gregorianrugs.com,1,4800000,Oriental Rugs,"Eligible. 1 showroom in Newton MA. 40000 sqft. 1x40000x120."
MattressGrove,mattressgrove.com,1,800000,Mattresses,"Eligible. 1 location in Greensboro NC. 1x4000x200."
Melie Bianco Wholesale,www.meliebiancowholesale.com,0,,Handbags,"INELIGIBLE. Wholesale/B2B-only."
TANFUL by Heidi,tanfulbyheidi.com,0,,Tanning Products,"Eligible. Online only."
Clampett Studio,clampettstudio.com,0,,Animation Art,"Eligible. Online only."
OSNO,osno.ca,0,,Children's Snowsuits,"Eligible. Online only."
MORPHIT SEA MOSS,morphitseamoss.com,0,,Sea Moss Supplements,"Eligible. DTC online only."
WILE,wilescents.com,0,,Fragrance,"Eligible. Sold via stockists; no brand-owned retail."
Relaxation Tea,relaxationtea.com,0,,Herbal Tea,"Eligible. DTC online only."
Olu Olu Foods,www.oluolufoods.com,0,,Afro-Caribbean Food,"Eligible. Online and stockists; no brand-owned retail."
Thrift D Vintage Clothing,www.thriftdvintageclothing.com,0,,Vintage Apparel,"Eligible. Online only."
CNT Racing,www.cntracing.com,1,450000,Auto Parts,"Eligible. 1 location in Hayward CA. 1x3000x150."
jaltest diagnostic tools,dieseltruckdiagnostictools.au,0,,Diagnostic Equipment,"INELIGIBLE. Wholesale/B2B-only."
Buck Wild Bohemian,buckwildbohemian.com,0,,Apparel,"Eligible. No physical stores found."
Effortless Beaute,effortless-beaute-toronto.myshopify.com,1,350000,Beauty Salon,"Eligible. 1 salon at 250 Wellington St W Toronto."
Sweet Expressions,sweetexpressionsbygeri.com,1,450000,Candy/Chocolates,"Eligible. 1 store in Denville NJ. 1x2500x180."
TheCoSpot,thecospot.com,0,,Retail,"Eligible. No physical retail found."
Simply Torn Boutique,simplytorn.shop,2,500000,Women's Apparel,"Eligible. 2 stores: Ada OH and Bellefontaine OH."
July Body,julybody.com,0,,Skincare,"Eligible. Online only."
Spice Range,spicerange.com,0,,Indian Groceries,"Eligible. Online only."
Big Bear Lifting,bigbearlifting.com.au,0,,Powerlifting Equipment,"Eligible. Australian lifting gear. Online only."
Jack & Becky,jackandbeckycloseouts.com,0,,Closeouts,"INELIGIBLE. Wholesale/B2B closeouts only."
GooseWaddle Wholesale,goosewaddlewholesale.com,0,,Baby Products,"INELIGIBLE. Wholesale/B2B-only."
Unna Bakery,unnabakery.com,1,350000,Swedish Cookies,"Eligible. 1 bakery at 164 Bleecker St NYC."
Tap N Roll Singles,tapnrollsingles.com,0,,Trading Cards,"Eligible. Offsite warehouse; pickup only; no retail storefront."
Apple Rose Beauty,www.applerosebeauty.com,0,,Skincare,"Eligible. Online and retail partners; no brand-owned stores."
Matt Naughtin,matt-naughtin.myshopify.com,0,,Retail,"Eligible. No physical retail found."
BusyBdy,busybdy.com,0,,Apparel,"Eligible. No physical retail found."
East West Machines,eastwestmachines.com,0,,Machinery,"Eligible. B2B industrial; no consumer retail."
Indigo Club,indigoclub.us,0,,Denim,"Eligible. Pre-launch. No open stores yet."
hypesub,hypesub.com,0,,Streetwear subscription boxes,"Online-only mystery box service. No brand-owned physical retail."
White Earth Enterprises,white-earth-enterprises-business-products.myshopify.com,0,,Promotional products,"INELIGIBLE: Wholesale/B2B-only."
Liberty Safes of College Station,libertysafeofcollegestation.com,0,,Safes,"INELIGIBLE: Firearms/weapons. Sells gun safes."
Wristband Giant Canada,www.wristbandgiant.ca,0,,Event wristbands,"INELIGIBLE: Wholesale/B2B-only."
Cheapo Depot 2,cheapoliberty.com,2,1500000,Liquidation merchandise,"2 stores in Prairie du Chien WI and Grove OK. 2x3000x250."
Amara Avenue,www.amaraavenue.com,0,,Women's and men's fashion,"Online-only. No brand-owned physical retail."
Kafune hair,kafunehair.com,0,,Lace wigs and hair care,"Online-only. No brand-owned physical retail."
David Beavis Fine Art,davidkbeavis.com,2,840000,Fine art photography,"2 galleries: Park City UT and Naples FL. 2x2000x350x0.6."
FloorPlay Socks,floorplaysocks.com,4,1200000,Socks and hosiery,"4 stores in Toronto area. 4x1500x250."
Lansinoh IE,www.lansinoh.ie,0,,Breastfeeding products,"Online DTC in Ireland. No brand-owned retail."
The Furniture Nest,thefurniture-nest.com,1,350000,Furniture and mattresses,"1 store at Twilley Shopping Center Salisbury MD. 1x2500x140."
Softlips Lip Balm,softlips.com,0,,Lip care,"Online DTC. No brand-owned physical retail."
Log Cabin Vintage,www.logcabinvintage.com,0,,Vintage children's books,"Online-only. No brand-owned physical retail."
Lit Lab Co.,litlab.us,0,,Candles and fragrance,"Online-only. No brand-owned physical retail."
Moraine,www.shop-moraine.com,0,,Unknown,"Website not found. Assumed online-only."
Clemson Tiger Traditions,tigertraditions.com,0,,College merchandise,"Online-only. No brand-owned physical retail."
Bootitude,www.bootitude.net,0,,Western boots,"Online retailer. No permanent retail."
Olive & Pique,oliveandpique.com,0,,Hats and headwear,"Online-only. No brand-owned physical retail."
Polish Pottery Pantry,polishpotterypantry.com,0,,Polish pottery and linens,"Online-only. No brand-owned physical retail."
Rock Deco Diamonds,rockdeco.com,1,350000,Natural diamonds and gemstones,"1 Santa Fe location. 1x1500x233."
official-adamo,www.adamoco.com.au,0,,Tote bags and accessories,"Online-only Australian brand. No brand-owned physical retail."
Fort Worth Streets Boutique,fortworthstreetsboutique.com,1,300000,Women's clothing and jewelry,"1 boutique in Fort Worth. 1x1500x200."
Arte Corazon,artecorazon.com,0,,Clothing and accessories,"Online retailer in Costa Rica. No brand-owned physical retail."
Wishlist Shop,www.wishlistshop.com,0,,Gifts/curated products,"Assumed online-only."
ReVibe Gear,revibegear.com,0,,Vibrating massage balls,"Online-only wellness product. No brand-owned physical retail."
The Haf-Clip,thehafclip.com,0,,Bike accessories,"Online-only. No brand-owned physical retail."
zimfit,zimfitmums.com,0,,Waist trainers and fitness wear,"Online-only. No brand-owned physical retail."
NovaTropes,www.novatropes.com,0,,Nootropic supplements,"Online DTC. No brand-owned physical retail."
Stoke,www.stokestove.com,0,,Portable pizza ovens,"Online-only. No brand-owned physical retail."
Botanic Bronze,botanic-bronze.com,0,,Self-tanning and skincare,"Online-only. No brand-owned physical retail."
TRVRS Creative,www.trvrsoutdoors.com,0,,Outdoor apparel,"Online-only. No brand-owned physical retail."
Sweet Valley Tees,sweetvalleytees.com,0,,Agriculture-themed apparel,"Online-only. No brand-owned physical retail."
Galaxy Natural Flavours,galaxyflavours.com,0,,Food flavourings,"INELIGIBLE: Wholesale/B2B-only."
Confidence By Char,confidencebychar.com,0,,Confidence coaching/products,"Assumed online-only."
Closet From Hell,closetfromhell.com,0,,Vintage clothing,"Online reseller. No brand-owned physical retail."
Galleri,galleri.shop,0,,Art prints,"Online art marketplace. No brand-owned physical retail."
Yoni Crystals,yonicrystals.love,0,,Intimacy crystals,"Online-only. No brand-owned physical retail."
Shimmerz Paints,www.shimmerzpaints.com,0,,Craft paints,"Online-only. No brand-owned physical retail."
$8 Jewelry with Janet Morgan,www.tmstbling.com,0,,Fashion jewelry,"Online-only. No brand-owned physical retail."
Boutique Sisi,www.boutiquesisi.com,1,250000,Women's fashion and dance apparel,"1 store at 361 Victoria Ave Westmount QC. 1x1500x167."
SERT,sert-us.myshopify.com,0,,Mattresses/bedding,"Assumed mattress brand. No brand-owned physical retail."
Angus Martin Art,www.angusmartinart.com,0,,Art prints and originals,"Online-only. No brand-owned physical retail."
fruit de la vie juice co.,fruitdelavie.com,2,600000,Cold-pressed juice,"2 Winnipeg locations. 2x1500x200."
Fatty Pancake,fattypancake.com,0,,Reptile-themed apparel,"Online-only. No brand-owned physical retail."
Laminates and Things,laminatesandthings.com,0,,Woodworking materials,"INELIGIBLE: Wholesale/B2B-only."
Prospect Coffee Roasters,www.prospectcoffee.com,1,280000,Specialty coffee,"1 coffee bar at 92 S Laurel St Ventura CA. 1x800x350."
The Rose Spa Of Lake Mary,shoptheroselakemary.com,1,400000,Med spa and skincare,"1 med spa at 156 N 4th St Lake Mary FL. 1x2000x200."
The Animal House,theanimalhouse.net,3,900000,Pet supplies,"3 Maine locations. 3x2000x150."
Elephant Floors,elephantfloors.shop,1,450000,Flooring,"1 showroom at 950 E El Camino Real Sunnyvale CA. 1x3000x150."
SudsLab,www.suds-lab.com,0,,Car detailing products,"Online-only. No brand-owned physical retail."
Bucker Creek Ranch LLC,www.buckercreekranch.com,0,,Wagyu beef and jerky,"Eligible. Ranch and e-commerce only. No retail."
ZIPCovers,zipcovers.com,0,,Custom patio furniture covers,"Eligible. Online-only. No physical retail."
Little Loves Organics,shoplittlelovesorganics.com,0,,Organic baby products,"Eligible. No retail locations found."
OnAdditive,onadditive.com,0,,Supplements,"Eligible. Limited public info. No retail found."
GutterCleaningBusiness.com,guttercleaningbusiness.com,0,,Gutter cleaning equipment,"Eligible. No retail."
Dana LeBlanc Designs,www.danaleblanc.com,0,,Handmade beaded jewelry,"Eligible. Online jewelry brand. No physical retail."
Elitech Technology Inc,www.ca.elitech.shop,0,,Temperature loggers and HVAC equipment,"Eligible. B2B/pro equipment. No consumer retail."
Zhiiva Skincare Inc,zhiiva.com,0,,Natural skincare serums,"Eligible. Online skincare brand. No retail."
PacBak,pacbak.com,0,,Outdoor gear and vacuum sealers,"Eligible. Online. No retail."
rolfeandwills,www.rolfeandwills.com,0,,Clothing,"Eligible. No retail found."
BasuraGang,basuragang.com,0,,Clothing and merchandise,"Eligible. Online. No retail."
thewatchmakersshop,www.thewatchmakersshop.com,1,25200,Watch repair and sales,"Eligible. 1 store in Grove Arcade Asheville NC."
wondermachines-europe,global.wondermachines.com,0,,Unknown,"Eligible. No retail found."
GOLDEN EARS SPECIALTY STORE,www.goldenearsspecialtystore.com,1,41250,Snacks and specialty foods,"Eligible. 1 store in Maple Ridge BC."
XO Resource Center,resources.xopublish.com,0,,Christian marriage books,"Eligible. Online resources. No retail."
sheet-music-now-dealer,dealer.sheetmusicnow.com,0,,Digital sheet music,"INELIGIBLE. B2B dealer portal."
Noah Supply,www.noahsupply.com,0,,Janitorial supplies,"INELIGIBLE. B2B distributor."
Little Rabbit Sign Co,littlerabbitsignco.com,0,,Catholic handmade products,"Eligible. Online. No retail."
Camp Rockmont Events,camp-rockmont-events.myshopify.com,0,,Camp merchandise,"Eligible. Camp merch store. No retail."
Dog Rescue Coffee Company,dogrescuecoffeecompany.com,0,,Coffee and dog treats,"Eligible. Online coffee brand. No retail."
Cursed Camp Studios,cursedcampstudios-store.com,0,,Hand-painted hockey masks,"Eligible. Online. No retail."
Allison Craft Designs,www.allisoncraftdesigns.com,0,,Artisan jewelry,"Eligible. Online. No retail."
Food Huggers Distributors,food-huggers-distributors.myshopify.com,0,,Silicone food savers,"INELIGIBLE. Wholesale/B2B-only."
Fur Accents,furaccents.com,1,90000,Faux fur home decor,"Eligible. 1 showroom in Orange CA."
Excitement Smokin PA,iloveexcitementsmokin.com,0,,Smoking accessories,"INELIGIBLE. Tobacco/vaping/smoke shop."
Anima Mea,shopanimamea.com,0,,Jewelry,"Eligible. Online. No retail."
Emmy's Beads,shopemmysbeads.com,0,,Beaded accessories,"Eligible. Online. No retail."
TOSCA STYLE,toscastyle.com,0,,Women's apparel,"Eligible. No retail found."
Peninsula Prints,peninsula-prints.com,0,,Block prints and art,"Eligible. Online. No retail."
The Lolo Baby,www.thelolobaby.com,0,,Breastfeeding carrier,"Eligible. Online. No retail."
Happy Bohemians,happybohemians.com,0,,Bohemian clothing,"Eligible. Online. No retail."
Mattress Innovations,www.mattressinnovations.com,1,240000,Mattresses,"Eligible. 1 store in Miamisburg OH."
Sticks and Scones Cakes,sticksandsconescakes.com,1,64800,Custom bakery,"Eligible. 1 bakery in London ON."
HONEY PINK,honeypink.com,0,,Women's apparel,"Eligible. Online. No retail."
Litquidity,litquidity-capital.myshopify.com,0,,Finance meme merchandise,"Eligible. Online merch. No retail."
Dream Team,dreamteam.shop,0,,Content creator merchandise,"Eligible. Online merch. No retail."
Terratorium,www.terratoriumwines.com,0,,Wine,"Eligible. Online wine. No retail."
Darci,darcistore.shop,0,,Celebrity merchandise,"Eligible. Online merch. No retail."
Glowstone.com,www.glowstone.com,0,,Glow-in-the-dark stones,"Eligible. Online. No retail."
CarMD,carmd.com,0,,Vehicle diagnostics,"Eligible. Online automotive tech. No retail."
Mackinac Memories,mackinacislandmemories.com,0,,Books and photography,"Eligible. Online. No retail."
LaceAnchors,laceanchors.com,0,,No-tie shoelace systems,"Eligible. Online. No retail."
Coast Spas Lethbridge,coastspaslethbridge.com,0,,Hot tubs and spas,"Eligible. Online. No confirmed retail showroom."
NTOA,shopntoa.org,0,,Tactical apparel merchandise,"Eligible. NTOA-branded apparel. No retail."
Make Your House A Home,makeyourhouseahomewhitchurch.com,1,30800,Homeware,"Eligible. 1 store in Whitchurch UK."
OJOS PUERTO RICO CLINICA,ojos-puerto-rico-clinica.myshopify.com,0,,Eye care products,"Eligible. Eye clinic online shop. No retail store."
Sew Southern Designs,www.sewsoutherndesigns.shop,1,25200,Boutique clothing,"Eligible. 1 boutique in Milan TN."
Watermelon Pictures,shop.watermelonpictures.com,0,,Film merchandise,"Eligible. Film company merch. No retail."
Elisabeth Weinstock,www.elisabethweinstock.com,1,180000,Luxury leather goods,"Eligible. 1 flagship store in LA."
Tender Loving Coffee,www.tenderlovingcoffee.com,1,57200,Coffee and cafe,"Eligible. 1 cafe in Chico CA."
"""

rows = []
reader = csv.reader(io.StringIO(raw_data.strip()))
for row in reader:
    if len(row) == 6:
        rows.append(row)

with open(output_file, 'a', newline='', encoding='utf-8') as f:
    writer = csv.writer(f)
    writer.writerows(rows)

print(f"Appended {len(rows)} rows")
