import csv
import os

output_file = "/workspace/retail_location_validation_results.csv"
header = ["Name", "Website", "Number of Retail Locations", "Predicted Revenue", "Product Type", "Reasoning"]

batch1_rows = [
    ["Hug Sleep Inc.", "hugsleep.com", "0", "", "Wearable blankets and sleep accessories", "Online-only DTC. Sleep Pod products via website and Amazon. No physical retail."],
    ["Cherish These", "cherishthese.com", "0", "", "Jewelry and accessories", "Online jewelry retailer. No brand-owned store locations found."],
    ["Kong Performance", "www.kongperformance.com", "0", "", "High-performance automotive parts", "Online retailer. Chester Heights PA is warehouse/office. Sells through authorized dealers."],
    ["ZIPCushions", "zipcushions.com", "1", "700000", "Custom indoor/outdoor cushions", "1 showroom at 1499 W 120th Ave Westminster CO. Home decor. 1500 sqft x $450/sqft."],
    ["Rogersound Labs", "rslspeakers.com", "0", "", "Speakers and audio equipment", "Factory-direct online since 1970. Calabasas office. No retail locations."],
    ["Ludwig Fine Wine", "ludwigsfinewine.com", "1", "1000000", "Wine and spirits", "1 retail store at 431 San Anselmo Ave CA. 2000 sqft x $500/sqft. Open 7 days."],
    ["Bellaucci", "bellaucci.com", "0", "", "Leather goods and accessories", "Online retailer. No physical store locations found."],
    ["German Car Accessories", "german-car-accessories.com", "0", "", "German car parts and accessories", "Online only. Scottsdale AZ warehouse. Audi/BMW/Mercedes parts."],
    ["MeMoi-DS", "memoi-ds.myshopify.com", "0", "", "Hosiery shapewear and leggings", "Online and third-party (Macy's JCPenney). No brand-owned retail."],
    ["Diabetic Supplies Unlimited", "www.diabeticsuppliesunlimited.com", "0", "", "Diabetic medical supplies", "Online only. Mount Sinai NY office/warehouse. Buys and sells supplies."],
    ["Tradition Hardware", "www.traditionhardware.com", "0", "", "Solid brass hardware", "Online-only DTC. Salt Lake City area. No physical stores."],
    ["1800ceiling", "www.1800ceiling.com", "0", "", "Ceiling products HVAC LED lighting", "Online only. Long Island warehouse. No retail showrooms."],
    ["SimPure", "www.simpurelife.com", "0", "", "Air and water filtration products", "Online only. Membrane Solutions sub-brand. No retail locations."],
    ["Sun Tanning Store", "suntanningstore.com", "0", "", "Tanning beds and spray tan equipment", "Online only. Casper WY. Sells equipment not salon services. No retail."],
    ["EIGHTH DAY", "eighthdayskin.com", "0", "", "Scientific skincare", "Online and Neiman Marcus. No brand-owned retail locations."],
    ["FCS Sneakers", "www.fcssneakers.com", "2", "3000000", "Collectible sneakers and streetwear", "2 brand-owned stores: Rosedale NY and Deer Park NY. 4000 sqft total x $750/sqft."],
    ["EzLift Bed", "ezliftbed.com", "0", "", "Mobility beds and sleep systems", "Store locator shows dealers only. No brand-owned retail."],
    ["Vatic Pro", "vaticpro.com", "0", "", "Pickleball paddles and gear", "Online and authorized retailers. Orange County based. No brand-owned stores."],
    ["Heart Healthy Homes", "www.hearthealthyhomes.com", "0", "", "Standard Process supplements", "Online supplement retailer. No physical locations."],
    ["RTS Tactical", "www.rtstactical.com", "0", "", "Body armor and tactical gear", "Online manufacturer. Body armor/shields not firearms. No retail locations."],
    ["Bubble Skincare", "hellobubble.com", "0", "", "Skincare for teens", "Store locator shows Ulta Walmart CVS. No brand-owned retail."],
    ["C. Richard's Leather", "www.crichardsleather.com", "0", "", "Custom leather patch hats", "Online only. Maine workshop. No retail storefront."],
    ["Optics Force", "opticsforce.com", "1", "1000000", "Optics rifle scopes outdoor gear", "1 retail at 71 Union Ave Brooklyn NY. 2000 sqft x $500/sqft."],
    ["Wallplates.com", "www.wallplates.com", "1", "1400000", "Decorative wall plates and switchplates", "1 Louisville KY location. Largest wall plate retailer. 3000 sqft x $450/sqft."],
    ["Sole Steals", "www.solesteals.com", "0", "", "Members-only sneaker webshop", "Online-only exclusive webshop. No physical locations."],
    ["C-IN2 New York", "www.c-in2.com", "0", "", "Premium men's underwear", "Online only. No physical store locations found."],
    ["Lash Next Door", "lashnextdoor.com", "0", "", "Beauty and fashion", "Online retailer. Amazon and app. No physical stores."],
    ["Howler Bike Park", "shop.howlerbikepark.com", "1", "1700000", "Mountain bikes and gear", "1 retail at 615 S Pickwick Ave Springfield MO. Bike shop. 3000 sqft x $550/sqft."],
    ["Fast Cash Strips LLC.", "www.fastcashstrips.com", "0", "", "Diabetic supply buyback service", "Online service. Buys unused test strips. No retail locations."],
    ["dfuser", "dfuser.com", "0", "", "Unknown - limited info", "Could not verify business. No retail information found."],
    ["Tini Lux", "tinilux.com", "0", "", "Jewelry and accessories", "Online jewelry brand. No physical store locations."],
    ["kate-minimalist", "kateminimalist.com", "0", "", "Home goods and minimalist lifestyle", "Online home/lifestyle retailer. No physical stores."],
    ["JDM Engine Pro", "jdmenginepro.com", "1", "1300000", "JDM engines and transmissions", "1 location at 760 E Lambert Rd La Habra CA. 3000 sqft x $450/sqft."],
    ["Future Kind", "www.futurekind.com", "0", "", "Vegan supplements", "Online-only vegan vitamins. No physical retail."],
    ["Stagecoach Meat Company", "stagecoachmeatcompany.com", "1", "900000", "Beef pork lamb and sausages", "1 retail meat market at 600 W 3rd Ave Wiggins CO. 2000 sqft x $450/sqft."],
    ["Sowears", "sowears.net", "0", "", "Women's fashion and dresses", "Online-only fashion retailer. No physical stores."],
    ["Stealth Hitches", "stealthhitches.com", "0", "", "Vehicle hitch systems", "Dealer/installer network only. No brand-owned retail."],
    ["Jane Pope Jewelry", "janepopejewelry.com", "1", "1100000", "Fine jewelry", "1 JP Studio Charleston SC by appointment. Luxury jewelry. 800 sqft x $1375/sqft."],
    ["Orion Van Gear", "orionvangear.com", "0", "", "Van conversion accessories", "Online only. Oregon-based. Roof racks solar. No retail."],
    ["The Cumin Club", "www.thecuminclub.com", "0", "", "Indian meal kits", "Store locator shows Sprouts Walmart Mariano's. Third-party only. No brand-owned retail."],
]

batch2_rows = [
    ["JapaneseChefsKnife.Com", "japanesechefsknife.com", "0", "", "Kitchen knives and cutlery", "Eligible. Sells Japanese chef knives online. Online-only retailer based in Seki Japan; no brand-owned physical retail locations."],
    ["Speed Cleaning", "speedcleaning.com", "0", "", "Professional cleaning products and tools", "Eligible. Sells cleaning supplies (mops, cleaners, equipment) to consumers and B2B. Online-only; no brand-owned retail stores."],
    ["DARLIN'", "darlinbrand.com", "0", "", "Americana-inspired apparel and accessories", "Eligible. Sells clothing, hats, swimwear, accessories. Online-only; no brand-owned physical retail locations."],
    ["Xtreme Caliber Performance LTD", "xtremecaliberperformance.ca", "0", "", "Automotive diesel tuning and performance parts", "Eligible. Sells diesel truck tuning, parts, remote tuning services. Vancouver Island-based; online/remote only; no retail storefront."],
    ["Lakeshore Metal Decor", "www.lakeshoremetaldecor.com", "0", "", "Custom metal signs and personalized home decor", "Eligible. Sells metal wall art, monograms, personalized gifts. Online-only (Shopify + Amazon); no physical retail."],
    ["CurezPro", "curezpros.com", "0", "", "Unknown - limited public information", "Eligible. Domain returns limited search results; assumed consumer products. No retail locations found."],
    ["curaiy", "curaiy.com", "0", "", "Unknown - limited public information", "Eligible. Domain not prominently indexed; may relate to personal care. No retail locations found."],
    ["Foger Vapes", "fogervapes.com", "0", "", "Vaping devices and e-liquids", "INELIGIBLE. Primary product is tobacco/vaping (disposable vapes, nicotine e-liquids). Excluded per Phase 1."],
    ["Vitruline", "vitruline.com", "0", "", "Eyewear - limited public information", "Eligible. Domain returns limited results; may relate to eyewear. No retail locations found."],
    ["L'entrepot de la Reno", "entrepotdelareno.com", "3", "3750000", "Construction materials and renovation supplies", "Eligible. Sells flooring, bathrooms, kitchens, lighting. 3 brand-owned Quebec locations: Quebec City, Trois-Rivieres, Brossard. Revenue: 3 x 2500 sqft x $500/sqft x 1.0 = ~$3.75M."],
    ["Pioneer Apparel", "pioneerapparel.com", "1", "3500000", "Wholesale urban/contemporary apparel", "Eligible. Sells mens, womens, kids clothing. 1 retail at 5369 Buford Hwy, Doraville GA. Revenue: 1 x 5000 sqft x $700/sqft x 1.0 = ~$3.5M."],
    ["The Toast Podcast", "www.thetoastpodcast.com", "0", "", "Podcast and merchandise", "Eligible. Entertainment/podcast with merch (apparel, accessories). Online-only; no physical retail."],
    ["Woodline Parts", "www.woodlineparts.com", "0", "", "Woodworking router bits and accessories", "Eligible. Sells router bits, shaper cutters, bearings, woodworking tools. Online-only (woodline.com); no retail locations."],
    ["rosycomfy.com", "www.rosycomfy.com", "0", "", "Women's loungewear and pajamas", "Eligible. Sells loungewear sets, pajamas, intimates. Online-only; no retail locations."],
    ["PiShock", "shopinthestorm.com", "0", "", "Shock collar devices for gaming/entertainment", "Eligible. Sells hub and shocker devices for streamers. Online-only; no retail locations."],
    ["War Tribe", "wartribegear.com", "0", "", "Martial arts and BJJ apparel and gear", "Eligible. Sells gis, rash guards, grappling shorts, hoodies. Online-only; no retail locations."],
    ["BowlersParadise.com", "www.bowlersparadise.com", "0", "", "Bowling balls bags shoes accessories", "Eligible. Sells bowling equipment from major brands. Online-only (Elk Grove CA operations); no retail storefront."],
    ["Mason Jar Lifestyle", "masonjarlifestyle.com", "0", "", "Mason jar lids and accessories", "Eligible. Sells storage lids, straw lids, fermentation accessories. Online-only (Shopify + Amazon); no retail."],
    ["Protein Chefs", "proteinchefs.com", "0", "", "Meal delivery service", "Eligible. Chef-prepared meal prep delivery in Ontario. Delivery-only; no retail locations."],
    ["BNR Motorsports", "bnr-motorsports.myshopify.com", "1", "1200000", "ATV and off-road vehicle parts and services", "Eligible. Sells parts, offers race shop services. 1 location at 12037 South Ave, North Lima OH. Revenue: 1 x 4000 sqft x $300/sqft x 1.0 = ~$1.2M."],
    ["Coconu", "coconu.com", "0", "", "Natural organic personal lubricants", "Eligible. Primary product is coconut oil lubricants. Online-only; no retail locations."],
    ["SUPERCAR GARAGE ATL", "supercargarageatl.com", "1", "1500000", "McLaren supercar service and parts", "Eligible. McLaren specialty service. 1 location at 3111 Moon Station Rd NW, Kennesaw GA. Revenue: 1 x 5000 sqft x $300/sqft x 1.0 = ~$1.5M."],
    ["River Street Sweets", "www.riverstreetsweets.com", "2", "2500000", "Pralines candy fudge ice cream", "Eligible. Gourmet candy and confections. 2 Savannah GA locations (River Street, Broughton St). Revenue: 2 x 2500 sqft x $500/sqft x 1.0 = ~$2.5M."],
    ["Viberg Wholesale", "wholesale.viberg.com", "0", "", "Work boots - wholesale only", "INELIGIBLE. Wholesale/B2B-only portal for Viberg boots. Excluded per Phase 1."],
    ["Talley & Twine Watch Company", "talleyandtwine.com", "0", "", "Watches and watch bands", "Eligible. Sells watches $175-$255. Online-only; no retail locations."],
    ["Ripple Foods", "ripplefoods.com", "0", "", "Plant-based pea milk", "Eligible. Sells pea-based milk through retailers and D2C. No brand-owned retail; third-party distribution only."],
    ["Demon United", "demon-united.com", "0", "", "Snowboarding skiing BMX protective gear", "Eligible. Sells D3O impact protection for action sports. Online + Amazon; no brand-owned retail."],
    ["Wildly Organic", "wildlyorganic.com", "0", "", "Organic health foods and skin care", "Eligible. Sells organic foods, coconut oil, natural products. Online primary; some third-party retail; no brand-owned stores."],
    ["The Rug Decor", "therugdecor.com", "0", "", "Handcrafted area rugs", "Eligible. Sells hand-knotted, hand-tufted rugs. Online-only; serves designers/wholesalers; no retail."],
    ["EZvacuum.com", "www.ezvacuum.com", "1", "450000", "Vacuum cleaners parts supplies", "Eligible. Sells vacuums and parts. 1 location at 8645 Phoenix Dr, Manassas VA (pickup). Revenue: 1 x 2000 sqft x $225/sqft x 1.0 = ~$450K."],
    ["The Armoury", "store.thearmoury.com", "4", "8000000", "Menswear and bespoke tailoring", "Eligible. Luxury menswear boutique. 4 locations: 2 NYC (Tribeca, Upper East Side), 2 Hong Kong. Revenue: 4 x 2000 sqft x $1000/sqft x 1.0 = ~$8M."],
    ["Crawl Space Ninja Store", "supply.crawlspaceninja.com", "0", "", "Crawl space repair supplies", "Eligible. Sells vapor barriers, dehumidifiers, drainage systems. Online with Huntsville TN pickup; pickup is warehouse not retail."],
    ["Maxivita", "maxivitaco.com", "0", "", "Cayenne-based vitality supplements", "Eligible. Sells liquid extract for circulation/stamina. Online-only; no retail locations."],
    ["Table & Twine", "tableandtwine.com", "0", "", "Chef-driven meal delivery", "Eligible. Meal subscription and delivery service. Charlotte-based delivery only; no retail locations."],
    ["Magal Jewelry", "secure.magaljewelry.com", "0", "", "Fine jewelry - made to order", "Eligible. Sells handcrafted jewelry, diamonds, 14K/18K gold. Online-only; no retail locations."],
    ["TrueTexasMerch", "truetexasmerch.com", "0", "", "Texas-themed apparel and merchandise", "Eligible. Sells Texas apparel, snacks, novelty items. Online-only; no retail locations."],
    ["Pool Nation USA", "www.poolnationusa.com", "0", "", "Above-ground and semi-in-ground pools", "Eligible. Sells swimming pools, filters, equipment. Online-only; no retail locations."],
    ["Chic Couture Online", "chiccoutureonline.com", "0", "", "Women's fashion and accessories", "Eligible. Sells dresses, tops, jewelry, swimwear. Online-only; no retail locations."],
    ["ConnecTen internet", "connecteninternet.com", "0", "", "Internet service provider", "Eligible. ISP offering home and mobile internet. Service business; no retail storefronts."],
    ["Italian Charms", "italiancharms.mx", "0", "", "Charm bracelets and individual charms", "Eligible. Sells Italian charm bracelets and charms. Online-only; no retail locations."],
]

batch3_rows = [
    ["andSons Chocolates", "and-sons.com", "1", "2600000", "Artisan chocolates and confections", "Eligible. 1 brand-owned store in Beverly Hills CA. Luxury chocolate shop. Revenue: 1 x 2000 sqft x $1300/sqft = ~$2.6M."],
    ["Gutter Garbs", "guttergarbs.com", "0", "", "Gutter guard products", "Eligible. Online-only. No brand-owned retail locations."],
    ["iMemories", "imemories.myshopify.com", "0", "", "Photo and video digitization service", "Eligible. Digital media conversion service. Online-only. No physical retail."],
    ["DeNova Detect", "denovadetect.com", "0", "", "Natural gas alarm detectors", "Eligible. Online-only. Sells safety detectors. No retail locations."],
    ["Few Will Hunt", "fewwillhunt.com", "0", "", "Outdoor apparel and gear", "Eligible. Online-only lifestyle brand. No brand-owned retail."],
    ["Sable Hotel Supply", "sablehotelsupply.com", "0", "", "Hotel and hospitality supplies", "INELIGIBLE. B2B/wholesale-only hotel supply business."],
    ["Roger Ximenez", "www.rogerximenez.com", "0", "", "Bespoke belts and leather accessories", "Eligible. Online custom leather goods. No physical retail storefront."],
    ["Hidden Hybrid Holsters", "hiddenhybridholsters.com", "0", "", "Gun holsters and firearm accessories", "INELIGIBLE. Firearms accessories. Excluded per Phase 1."],
    ["Town Shop", "www.townshop.com", "1", "945000", "Lingerie and intimate apparel", "Eligible. 1 brand-owned store in NYC Upper West Side. Revenue: 1 x 1500 sqft x $630/sqft = ~$945K."],
    ["Variant Alloy Wheels", "variantwheels.com", "0", "", "Custom alloy wheels", "Eligible. Online-only. Dealer network. No brand-owned retail."],
    ["CYSM PRO", "cysmpro.com", "0", "", "Shapewear and body shapers - wholesale", "INELIGIBLE. B2B/wholesale-only portal. Excluded per Phase 1."],
    ["Ark Splash Guards", "arksplashguards.com", "0", "", "Vehicle splash guards and mud flaps", "Eligible. Online-only. No physical retail."],
    ["Fabulous For Five", "fabulousforever.shop", "0", "", "Affordable fashion accessories", "Eligible. Online boutique. No physical retail."],
    ["Diamond Custom Machines", "www.melangers.com", "0", "", "Chocolate melangers and refining machines", "INELIGIBLE. B2B commercial equipment manufacturer."],
    ["Keto Brainz Nootropics", "ketobrainz.com", "0", "", "Keto nootropic supplements", "Eligible. Online-only supplement brand. No retail."],
    ["Rarify", "rarify.co", "0", "", "NFT and virtual currency infrastructure", "INELIGIBLE. Virtual currencies/NFT platform. Excluded per Phase 1."],
    ["UpriseAthlete", "upriseathlete.com", "0", "", "Athletic apparel and training", "Eligible. Online-only. No physical retail."],
    ["Bella Rose Quilts", "bellarosequilts.com", "0", "", "Quilting fabrics and supplies", "Eligible. Online quilting shop. No physical retail."],
    ["CloBombs", "clobombs.com", "0", "", "Bath bombs and bath products", "Eligible. Online-only. No physical retail."],
    ["Bifrost Gear", "www.bifrostgear.com", "0", "", "Tactical and weapon accessories", "INELIGIBLE. Weapon accessories/tactical gear. Excluded per Phase 1."],
    ["Summoraft", "summoraft.com", "0", "", "Unknown - limited information", "Eligible. Limited public info. No retail locations found."],
    ["PelviPulse", "pelvipulsepro.com", "0", "", "Pelvic floor exercise devices", "Eligible. Online-only wellness product. No retail."],
    ["Aquaterra Spas", "aquaterraspas.com", "0", "", "Hot tubs and spas", "Eligible. Online/dealer sales. No brand-owned retail showroom."],
    ["The Budget Mom", "shop.thebudgetmom.com", "0", "", "Budgeting planners and financial tools", "Eligible. Online store for budgeting products. No physical retail."],
    ["Air Freshener Marketing", "airfreshenermarketing.com", "0", "", "Custom promotional air fresheners", "INELIGIBLE. B2B promotional products company."],
    ["Marcus Pierce", "shopmarcuspierce.com", "0", "", "Fashion apparel", "Eligible. Online-only fashion brand. No physical retail."],
    ["Well Told", "welltolddesign.com", "0", "", "Custom map glassware and gifts", "Eligible. Online custom drinkware. No brand-owned retail."],
    ["INVISASOX", "www.invisasox.com", "0", "", "No-show socks", "Eligible. Online-only sock brand. No physical retail."],
    ["LandscapeDirect", "landscapedirect.ca", "0", "", "Landscape supplies", "Eligible. Online landscape supply. No brand-owned retail."],
    ["The Pattern Collective", "thepatterncollective.com", "0", "", "Sewing patterns and education", "Eligible. Online digital patterns. No physical retail."],
    ["omeuchip", "omeuchip.com", "0", "", "Unknown - limited information", "Eligible. Limited public info. No retail locations found."],
    ["Engineered Cooling Products", "ecp-radiator.com", "0", "", "Automotive radiators and cooling", "Eligible. Online/manufacturer direct. No brand-owned retail."],
    ["Red Label Abrasives", "www.redlabelabrasives.com", "0", "", "Sanding belts and abrasive products", "Eligible. Online manufacturer direct. No physical retail."],
    ["Sync Botanicals", "syncbotanicalsco.com", "0", "", "CBD products", "INELIGIBLE. Primary product is CBD. Excluded per Phase 1."],
    ["Podiums Direct", "podiumsdirect.com", "0", "", "Podiums and lecterns", "INELIGIBLE. B2B podiums/lecterns for businesses. Excluded per Phase 1."],
    ["Furniture Depot", "furnituredepot.ca", "2", "990000", "Furniture and home goods", "Eligible. 2 brand-owned stores in Ontario: Brampton and Mississauga. Revenue: 2 x 2000 sqft x $450/sqft x 0.55 = ~$990K."],
    ["Action Machine Inc", "www.actionmachineinc.com", "1", "270000", "Machine shop parts and services", "Eligible. 1 location at South Bend IN. Machine shop with retail parts. Revenue: 1 x 1500 sqft x $180/sqft = ~$270K."],
    ["Hypothermias.com", "www.hypothermias.com", "0", "", "Snow cone and shaved ice supplies", "Eligible. Online retailer of syrups and equipment. No brand-owned retail."],
    ["Oiwa Garage", "oiwagarage.co", "0", "", "Japanese car parts and builds", "Eligible. Online-only. No physical retail storefront."],
    ["Maya Kern", "store.mayakern.com", "0", "", "Art prints and illustrated merchandise", "Eligible. Online artist merch store. No physical retail."],
]

batch4_rows = [
    ["Ride Out Supply", "rideoutsupply.com", "0", "", "BMX and bike parts apparel accessories", "Eligible. Online-only retailer. No brand-owned physical retail locations found."],
    ["Serawise", "www.serawise.com", "0", "", "Unable to verify", "Unable to verify - website serawise.com not found in search results."],
    ["RoosRoast", "www.roosroast.com", "1", "900000", "Coffee cafe food", "Eligible. Brand-owned cafe at 1155 Rosewood St Ann Arbor MI. 1 location. Est: 2000 sqft x $450/sqft."],
    ["Ourland Outdoor", "ourlandoutdoor.com", "0", "", "Outdoor apparel and gear", "Eligible. Online-only. Address at Morgantown WV is warehouse/office not retail."],
    ["UnitedSign", "www.unitedsign.com", "0", "", "Signage for gas stations and c-stores", "Eligible. Signage supplier (not tobacco retailer). Online/phone orders only. No brand-owned retail."],
    ["Iron Accents", "www.ironaccents.com", "2", "1350000", "Home decor furniture wrought iron", "Eligible. 2 brand-owned stores: Clermont GA and 135 E Pike St Lawrenceville GA. Est: 2 x 3000 sqft x $225/sqft."],
    ["Ryno Power", "rynopower.com", "0", "", "Sports supplements", "Eligible. Online and dealer network only. No brand-owned retail stores."],
    ["KEVKO", "kevkoracing.com", "0", "", "Racing engine parts oil pans", "Eligible. Manufacturing facility in Fairmont MN. Online/dealer sales. No brand-owned retail."],
    ["Secretbargainshop", "secretbargainshop.com", "0", "", "Wholesale cosmetics and accessories", "INELIGIBLE. Wholesale/B2B-only business model."],
    ["Project Orochi", "projectorochi.com", "0", "", "Anime and video game apparel", "Eligible. Online-only. No brand-owned physical retail."],
    ["Hudson Henry Photography", "shop.hudsonhenry.com", "0", "", "Photography courses camera gear", "Eligible. Online education and gear sales. No physical retail."],
    ["Pet And Home", "petandhomeco.com", "0", "", "Pet-friendly sofa covers", "Eligible. Online-only. No brand-owned retail locations."],
    ["Felicityworldwide", "felicityworldwide.com", "0", "", "Jewelry personalized accessories", "Eligible. Online jewelry retailer. No retail locations."],
    ["Print Natural", "printnatural.com", "0", "", "Custom organic apparel printing", "INELIGIBLE. B2B/wholesale custom printing and fulfillment. Bulk orders only."],
    ["Wheel Center Caps", "wheelcentercaps.com", "0", "", "Automotive center caps wheels tires", "Eligible. Pico Rivera CA location is warehouse/order fulfillment. No walk-in retail hours."],
    ["Advanced Food Intolerance Labs", "advancedfoodintolerancelabs.com", "0", "", "At-home food intolerance testing", "Eligible. Lab testing service. Online/direct. No physical retail."],
    ["Plum Practicewear", "plumpracticewear.com", "0", "", "Gymnastics leotards dancewear", "Eligible. Spring Lake Heights NJ is office. Online-only. No retail store."],
    ["Gen5DIY", "www.gen5diy.com", "0", "", "Automotive DIY harnesses and parts", "Eligible. Online-only. No brand-owned retail."],
    ["NorCal Fire & Grill", "www.norcalfireandgrill.com", "0", "", "Fireplaces outdoor grills pizza ovens", "Eligible. Online retailer. No physical retail locations."],
    ["Boyzclub", "boyzclub.com", "0", "", "Casual apparel graphic tees", "Eligible. Online-only. No brand-owned retail."],
    ["That's it. Nutrition", "www.thatsitfruit.com", "0", "", "Fruit bars snacks", "Eligible. Sold at Costco, Whole Foods, Target etc. No brand-owned retail. Third-party distribution only."],
    ["JoyJolt", "www.joyjolt.com", "0", "", "Drinkware glassware", "Eligible. Sold at Macy's, Home Depot. No brand-owned retail stores."],
    ["San Antonio JDM Engines", "sanantoniojdmengines.com", "0", "", "JDM/KDM engines and transmissions", "Eligible. Online/phone orders. No physical retail storefront."],
    ["Smile Makers", "smilemakerscollection.com", "0", "", "Intimate wellness products", "Eligible. Sold at Sephora, Anthropologie. Online and third-party retail. No brand-owned stores."],
    ["Livable Hair", "livablehair.com", "0", "", "Nano bead hair extensions", "Eligible. Online-only. No physical retail."],
    ["Insurance Exam Queen", "insuranceexamqueen.myshopify.com", "0", "", "Insurance exam prep courses", "Eligible. Online education. No physical retail."],
    ["WTA Technologies", "wta.vet", "0", "", "Veterinary reproductive technology", "Eligible. B2B veterinary equipment and services. College Station TX. No consumer retail."],
    ["Laser Safety Industries", "lasersafetyindustries.com", "0", "", "Laser safety equipment", "INELIGIBLE. B2B-only. Industrial and government contracts."],
    ["Alan Jackson Official Webstore", "store.alanjackson.com", "0", "", "Music merchandise apparel", "Eligible. Online-only official merchandise. No physical retail."],
    ["TrueTrac", "truetrac.com", "0", "", "Automotive differentials", "Eligible. Sold through dealers. No brand-owned retail."],
    ["Maverick Industrial Sales", "maverickindustrialsales.com", "0", "", "Surplus industrial equipment", "INELIGIBLE. B2B-only. Industrial surplus and asset recovery."],
    ["Metabolic Nutrition", "www.metabolicnutrition.com", "0", "", "Fitness supplements", "Eligible. Online and Amazon. No brand-owned retail."],
    ["KGB Swimbaits", "kgbswimbaits.com", "0", "", "Fishing swimbaits", "Eligible. Online and dealer network. No brand-owned retail."],
    ["Leilanis Leis", "leilanisleis.com", "3", "1800000", "Hawaiian leis Polynesian retail", "Eligible. 3 brand-owned locations: 5505 Clairemont Mesa Blvd San Diego, 5105 Cass St San Diego, 4749 S Maryland Pkwy Las Vegas. Est: 3 x 2000 sqft x $300/sqft."],
    ["Pro Speaker Parts", "prospeakerparts.com", "0", "", "Speaker components audio parts", "Eligible. B2B/manufacturer direct. No physical retail."],
    ["BAEZ", "www.baezonline.com", "0", "", "Unable to verify", "Unable to verify - baezonline.com not found in search results."],
    ["Simsima.co", "simsima.co", "0", "", "Unable to verify", "Unable to verify - simsima.co not found in search results."],
    ["Retro Soccer Kit", "retrosoccerkit.com", "0", "", "Retro soccer jerseys", "Eligible. Online-only. No physical retail."],
    ["Northwest Meadowscapes", "northwestmeadowscapes.com", "0", "", "Native seeds plants", "Eligible. Online and professional services. No brand-owned retail store."],
    ["Shaft Connect", "shaftconnect.com", "0", "", "Golf shafts club components", "Eligible. Online-only. No brand-owned retail."],
]

batch5_rows = [
    ["TRAK Kayaks", "www.trakkayaks.com", "0", "", "Outdoor recreation - folding kayaks and paddling gear", "Eligible. Online/D2C only. No brand-owned retail locations found."],
    ["Maya Jewelry", "mayajewelry.com", "1", "960000", "Body jewelry and fine jewelry", "Eligible. 1 brand-owned store at 542 Castro St San Francisco CA. 1200 sqft x $800 jewelry/sqft x 1.0 = $960K."],
    ["eurobahndynamics", "eurobahndynamics.com", "0", "", "Automotive aftermarket - carbon fiber parts and performance upgrades", "Eligible. Online-only retailer. No physical retail locations."],
    ["VS Tees", "vstees.com", "1", "560000", "Apparel - blank t-shirts and custom printing", "Eligible. 1 brand-owned location at 1316 S Main St #3 Los Angeles. 2000 sqft x $280 apparel/sqft x 1.0 = $560K."],
    ["Tea Runners", "tearunners.com", "0", "", "Tea subscription - loose leaf tea", "Eligible. Subscription e-commerce only. No physical retail locations."],
    ["SleepDreams", "sleepdreamco.com", "0", "", "Sleep products", "Eligible. Limited info. Appears online-only. No retail locations found."],
    ["Better Than Before Consignment", "shop.btbconsignments.com", "2", "3840000", "Consignment - used clothing and designer items", "Eligible. 2 brand-owned stores: Cullman AL and Decatur AL. 16000 sqft total. 2 x 8000 x $240 consignment/sqft x 1.0 = $3.84M."],
    ["Go Velure", "govelure.com", "0", "", "Lifestyle retail - fitness trackers perfumes fashion", "Eligible. Online-only. Diverse product mix. No physical retail."],
    ["Prime Barrel", "primebarrel.com", "0", "", "Spirits - single-barrel whiskey and bourbon", "Eligible. Online whiskey marketplace. No brand-owned retail."],
    ["SUSANNA CHOW", "susannachownyc.com", "0", "", "Luxury fashion - outerwear accessories jewelry", "Eligible. Online boutique. Production in Chinatown NYC but no retail storefront."],
    ["Armament Technology Inc.", "armament.com", "0", "", "Weapon sighting systems and optical combat equipment", "INELIGIBLE. Primary product is firearms/weapons optics. Excluded per policy."],
    ["Starfront Observatories", "shopify.starfront.space", "0", "", "Remote telescope hosting service - astrophotography", "Eligible. Service model. Not traditional retail. 0 retail locations."],
    ["Atwood Rope MFG", "atwoodrope.com", "0", "", "Rope and cordage manufacturing", "Eligible. Manufacturer in Mollersport OH. B2B/wholesale focus. No consumer retail store."],
    ["HerNaturals", "hernaturals.co", "0", "", "Natural hair care products", "Eligible. Online D2C hair care brand. No physical retail locations."],
    ["Maptote", "www.maptote.com", "0", "", "Tote bags and map-themed gifts", "Eligible. Online + Brooklyn studio. No retail store; pickup by arrangement only."],
    ["Nexenzo", "www.nexenzo.com", "0", "", "Unknown - limited search results", "Eligible. Domain returns limited results. Assumed online-only. 0 retail."],
    ["USA Tool Depot", "usatooldepot.com", "1", "1120000", "Professional tools and fasteners", "Eligible. 1 brand-owned store at 215 E 78th St Bloomington MN. 4000 sqft x $280 tools/sqft x 1.0 = $1.12M."],
    ["Dove Originals Trims", "doveoriginalstrims.com", "0", "", "Craft supplies - trims ribbons sewing notions", "Eligible. Online craft store. No physical retail."],
    ["PUPSENTIALS", "www.pupsentials.com", "0", "", "Pet apparel and custom embroidered accessories", "Eligible. Online custom pet apparel. No physical retail."],
    ["Try-Blue", "tryblue.org", "0", "", "Unknown - domain not clearly identified", "Eligible. tryblue.org search inconclusive. Assumed eligible. 0 retail."],
    ["Kelco Supply Company", "kelcosupply.com", "0", "", "Funeral and mortuary industry supplies", "INELIGIBLE. Wholesale/B2B-only. Serves funeral homes. Excluded per policy."],
    ["Ceretone Hearing Aids", "ceretone.com", "0", "", "OTC hearing aids", "Eligible. Online hearing aid retailer. No brand-owned retail locations."],
    ["Ergo Sky", "myergosky.com", "0", "", "Ergonomic office chairs", "Eligible. Online office chair retailer. No physical retail."],
    ["Main Street Forge", "mainstreetforge.com", "0", "", "Leather goods - belts wallets EDC", "Eligible. E-commerce leather goods. No physical retail."],
    ["306 Sports Cards", "www.306sportscards.com", "1", "560000", "Sports cards and collectibles", "Eligible. 1 brand-owned store at 718 Circle Dr E Saskatoon SK. 2000 sqft x $280 hobby/sqft x 1.0 = $560K."],
    ["Autobriva", "ipy7cy-kr.myshopify.com", "0", "", "Unknown - Shopify store", "Eligible. Generic Shopify URL. Limited info. Assumed online-only. 0 retail."],
    ["Bonka Bird Toys", "bonkabirdtoys.com", "1", "420000", "Bird toys and pet supplies", "Eligible. 1 brand-owned store at 5151 NE 12th Ave Fort Lauderdale FL. Walk-in Mon-Fri. 1500 sqft x $280 pet/sqft x 1.0 = $420K."],
    ["Toplux", "trytoplux.shop", "0", "", "Unknown - limited search results", "Eligible. trytoplux.shop returns limited results. Assumed online-only. 0 retail."],
    ["Seura", "seura.com", "0", "", "TV mirrors and lighted mirrors", "Eligible. Manufacturer in Green Bay WI. Sells through dealer network. No brand-owned retail showroom."],
    ["Mobi-mat Shop", "shop.mobi-mat.com", "0", "", "Beach and park accessibility mats", "Eligible. B2B/municipal focus. Online shop. No brand-owned retail."],
    ["TenThreeGraphics.com", "tenthreegraphics.com", "0", "", "Screen printing and custom merch", "Eligible. Screen printing company. Online/custom orders. No retail storefront."],
    ["Sportscards.com", "sportscards.com", "0", "", "Sports trading cards", "Eligible. Online sports card retailer. No physical retail."],
    ["Aloxxi Professional", "pro.aloxxi.com", "0", "", "Professional hair care and color", "INELIGIBLE. B2B/professional-only. Serves salons and stylists. Excluded per policy."],
    ["Lifekind", "lifekind.com", "0", "", "Organic mattresses and bedding", "Eligible. Online organic bedding. Made-to-order. No retail locations."],
    ["Heidi Gibson", "shop.heidigibson.com", "0", "", "Fine jewelry - engagement rings", "Eligible. Online jewelry design studio. No physical showroom."],
    ["Girlz Ink", "www.girlzink.com", "0", "", "Permanent makeup supplies and education", "Eligible. PMU supplies for artists. Online. No retail store."],
    ["Exactly Right Store", "exactlyrightstore.com", "0", "", "Podcast merchandise", "Eligible. Online merch for Exactly Right podcast network. No physical retail."],
    ["Speedrite Electric Fence Chargers", "www.speedritechargers.com", "0", "", "Electric fence energizers and livestock equipment", "Eligible. Operated by Valley Farm Supply. Online. No brand-owned retail."],
    ["MOMMYWHOLESALE.COM", "www.mommywholesale.com", "0", "", "Bags handbags accessories", "INELIGIBLE. B2B wholesale only. Requires business license. Excluded per policy."],
    ["Lynn's Discounts", "www.lynnsdiscounts.com", "1", "700000", "Discount retailer - varied merchandise", "Eligible. 1 brand-owned store at 197 Foothills Mall Dr Maryville TN. 2500 sqft x $280 discount/sqft x 1.0 = $700K."],
]

all_rows = batch1_rows + batch2_rows + batch3_rows + batch4_rows + batch5_rows

with open(output_file, 'w', newline='', encoding='utf-8') as f:
    writer = csv.writer(f)
    writer.writerow(header)
    writer.writerows(all_rows)

print(f"Wrote {len(all_rows)} rows to {output_file}")
